// Code generated by go-swagger; DO NOT EDIT.

package rate_category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new rate category API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for rate category API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetTravelExpenseRateCategory bs e t a find rate categories corresponding with sent data
*/
func (a *Client) GetTravelExpenseRateCategory(params *GetTravelExpenseRateCategoryParams, authInfo runtime.ClientAuthInfoWriter) (*GetTravelExpenseRateCategoryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTravelExpenseRateCategoryParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetTravelExpenseRateCategory",
		Method:             "GET",
		PathPattern:        "/travelExpense/rateCategory",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTravelExpenseRateCategoryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTravelExpenseRateCategoryOK), nil

}

/*
GetTravelExpenseRateCategoryID bs e t a get travel expense rate category by ID
*/
func (a *Client) GetTravelExpenseRateCategoryID(params *GetTravelExpenseRateCategoryIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetTravelExpenseRateCategoryIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTravelExpenseRateCategoryIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetTravelExpenseRateCategoryID",
		Method:             "GET",
		PathPattern:        "/travelExpense/rateCategory/{id}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTravelExpenseRateCategoryIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTravelExpenseRateCategoryIDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
