// Code generated by go-swagger; DO NOT EDIT.

package passenger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteTravelExpensePassengerIDParams creates a new DeleteTravelExpensePassengerIDParams object
// with the default values initialized.
func NewDeleteTravelExpensePassengerIDParams() *DeleteTravelExpensePassengerIDParams {
	var ()
	return &DeleteTravelExpensePassengerIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTravelExpensePassengerIDParamsWithTimeout creates a new DeleteTravelExpensePassengerIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteTravelExpensePassengerIDParamsWithTimeout(timeout time.Duration) *DeleteTravelExpensePassengerIDParams {
	var ()
	return &DeleteTravelExpensePassengerIDParams{

		timeout: timeout,
	}
}

// NewDeleteTravelExpensePassengerIDParamsWithContext creates a new DeleteTravelExpensePassengerIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteTravelExpensePassengerIDParamsWithContext(ctx context.Context) *DeleteTravelExpensePassengerIDParams {
	var ()
	return &DeleteTravelExpensePassengerIDParams{

		Context: ctx,
	}
}

// NewDeleteTravelExpensePassengerIDParamsWithHTTPClient creates a new DeleteTravelExpensePassengerIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteTravelExpensePassengerIDParamsWithHTTPClient(client *http.Client) *DeleteTravelExpensePassengerIDParams {
	var ()
	return &DeleteTravelExpensePassengerIDParams{
		HTTPClient: client,
	}
}

/*DeleteTravelExpensePassengerIDParams contains all the parameters to send to the API endpoint
for the delete travel expense passenger ID operation typically these are written to a http.Request
*/
type DeleteTravelExpensePassengerIDParams struct {

	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete travel expense passenger ID params
func (o *DeleteTravelExpensePassengerIDParams) WithTimeout(timeout time.Duration) *DeleteTravelExpensePassengerIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete travel expense passenger ID params
func (o *DeleteTravelExpensePassengerIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete travel expense passenger ID params
func (o *DeleteTravelExpensePassengerIDParams) WithContext(ctx context.Context) *DeleteTravelExpensePassengerIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete travel expense passenger ID params
func (o *DeleteTravelExpensePassengerIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete travel expense passenger ID params
func (o *DeleteTravelExpensePassengerIDParams) WithHTTPClient(client *http.Client) *DeleteTravelExpensePassengerIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete travel expense passenger ID params
func (o *DeleteTravelExpensePassengerIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete travel expense passenger ID params
func (o *DeleteTravelExpensePassengerIDParams) WithID(id int32) *DeleteTravelExpensePassengerIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete travel expense passenger ID params
func (o *DeleteTravelExpensePassengerIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTravelExpensePassengerIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
