// Code generated by go-swagger; DO NOT EDIT.

package passenger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTravelExpensePassengerParams creates a new GetTravelExpensePassengerParams object
// with the default values initialized.
func NewGetTravelExpensePassengerParams() *GetTravelExpensePassengerParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetTravelExpensePassengerParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTravelExpensePassengerParamsWithTimeout creates a new GetTravelExpensePassengerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTravelExpensePassengerParamsWithTimeout(timeout time.Duration) *GetTravelExpensePassengerParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetTravelExpensePassengerParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: timeout,
	}
}

// NewGetTravelExpensePassengerParamsWithContext creates a new GetTravelExpensePassengerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTravelExpensePassengerParamsWithContext(ctx context.Context) *GetTravelExpensePassengerParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetTravelExpensePassengerParams{
		Count: &countDefault,
		From:  &fromDefault,

		Context: ctx,
	}
}

// NewGetTravelExpensePassengerParamsWithHTTPClient creates a new GetTravelExpensePassengerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTravelExpensePassengerParamsWithHTTPClient(client *http.Client) *GetTravelExpensePassengerParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetTravelExpensePassengerParams{
		Count:      &countDefault,
		From:       &fromDefault,
		HTTPClient: client,
	}
}

/*GetTravelExpensePassengerParams contains all the parameters to send to the API endpoint
for the get travel expense passenger operation typically these are written to a http.Request
*/
type GetTravelExpensePassengerParams struct {

	/*Count
	  Number of elements to return

	*/
	Count *int64
	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*From
	  From index

	*/
	From *int64
	/*MileageAllowance
	  Equals

	*/
	MileageAllowance *string
	/*Name
	  Containing

	*/
	Name *string
	/*Sorting
	  Sorting pattern

	*/
	Sorting *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) WithTimeout(timeout time.Duration) *GetTravelExpensePassengerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) WithContext(ctx context.Context) *GetTravelExpensePassengerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) WithHTTPClient(client *http.Client) *GetTravelExpensePassengerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) WithCount(count *int64) *GetTravelExpensePassengerParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) SetCount(count *int64) {
	o.Count = count
}

// WithFields adds the fields to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) WithFields(fields *string) *GetTravelExpensePassengerParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFrom adds the from to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) WithFrom(from *int64) *GetTravelExpensePassengerParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) SetFrom(from *int64) {
	o.From = from
}

// WithMileageAllowance adds the mileageAllowance to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) WithMileageAllowance(mileageAllowance *string) *GetTravelExpensePassengerParams {
	o.SetMileageAllowance(mileageAllowance)
	return o
}

// SetMileageAllowance adds the mileageAllowance to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) SetMileageAllowance(mileageAllowance *string) {
	o.MileageAllowance = mileageAllowance
}

// WithName adds the name to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) WithName(name *string) *GetTravelExpensePassengerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) SetName(name *string) {
	o.Name = name
}

// WithSorting adds the sorting to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) WithSorting(sorting *string) *GetTravelExpensePassengerParams {
	o.SetSorting(sorting)
	return o
}

// SetSorting adds the sorting to the get travel expense passenger params
func (o *GetTravelExpensePassengerParams) SetSorting(sorting *string) {
	o.Sorting = sorting
}

// WriteToRequest writes these params to a swagger request
func (o *GetTravelExpensePassengerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.From != nil {

		// query param from
		var qrFrom int64
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := swag.FormatInt64(qrFrom)
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	if o.MileageAllowance != nil {

		// query param mileageAllowance
		var qrMileageAllowance string
		if o.MileageAllowance != nil {
			qrMileageAllowance = *o.MileageAllowance
		}
		qMileageAllowance := qrMileageAllowance
		if qMileageAllowance != "" {
			if err := r.SetQueryParam("mileageAllowance", qMileageAllowance); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Sorting != nil {

		// query param sorting
		var qrSorting string
		if o.Sorting != nil {
			qrSorting = *o.Sorting
		}
		qSorting := qrSorting
		if qSorting != "" {
			if err := r.SetQueryParam("sorting", qSorting); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
