// Code generated by go-swagger; DO NOT EDIT.

package passenger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPostTravelExpensePassengerParams creates a new PostTravelExpensePassengerParams object
// with the default values initialized.
func NewPostTravelExpensePassengerParams() *PostTravelExpensePassengerParams {
	var ()
	return &PostTravelExpensePassengerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTravelExpensePassengerParamsWithTimeout creates a new PostTravelExpensePassengerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTravelExpensePassengerParamsWithTimeout(timeout time.Duration) *PostTravelExpensePassengerParams {
	var ()
	return &PostTravelExpensePassengerParams{

		timeout: timeout,
	}
}

// NewPostTravelExpensePassengerParamsWithContext creates a new PostTravelExpensePassengerParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTravelExpensePassengerParamsWithContext(ctx context.Context) *PostTravelExpensePassengerParams {
	var ()
	return &PostTravelExpensePassengerParams{

		Context: ctx,
	}
}

// NewPostTravelExpensePassengerParamsWithHTTPClient creates a new PostTravelExpensePassengerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTravelExpensePassengerParamsWithHTTPClient(client *http.Client) *PostTravelExpensePassengerParams {
	var ()
	return &PostTravelExpensePassengerParams{
		HTTPClient: client,
	}
}

/*PostTravelExpensePassengerParams contains all the parameters to send to the API endpoint
for the post travel expense passenger operation typically these are written to a http.Request
*/
type PostTravelExpensePassengerParams struct {

	/*Body
	  JSON representing the new object to be created. Should not have ID and version set.

	*/
	Body *models.Passenger

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post travel expense passenger params
func (o *PostTravelExpensePassengerParams) WithTimeout(timeout time.Duration) *PostTravelExpensePassengerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post travel expense passenger params
func (o *PostTravelExpensePassengerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post travel expense passenger params
func (o *PostTravelExpensePassengerParams) WithContext(ctx context.Context) *PostTravelExpensePassengerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post travel expense passenger params
func (o *PostTravelExpensePassengerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post travel expense passenger params
func (o *PostTravelExpensePassengerParams) WithHTTPClient(client *http.Client) *PostTravelExpensePassengerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post travel expense passenger params
func (o *PostTravelExpensePassengerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post travel expense passenger params
func (o *PostTravelExpensePassengerParams) WithBody(body *models.Passenger) *PostTravelExpensePassengerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post travel expense passenger params
func (o *PostTravelExpensePassengerParams) SetBody(body *models.Passenger) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostTravelExpensePassengerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
