// Code generated by go-swagger; DO NOT EDIT.

package vat_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetLedgerVatTypeIDReader is a Reader for the GetLedgerVatTypeID structure.
type GetLedgerVatTypeIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLedgerVatTypeIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetLedgerVatTypeIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLedgerVatTypeIDOK creates a GetLedgerVatTypeIDOK with default headers values
func NewGetLedgerVatTypeIDOK() *GetLedgerVatTypeIDOK {
	return &GetLedgerVatTypeIDOK{}
}

/*GetLedgerVatTypeIDOK handles this case with default header values.

successful operation
*/
type GetLedgerVatTypeIDOK struct {
	Payload *models.ResponseWrapperVatType
}

func (o *GetLedgerVatTypeIDOK) Error() string {
	return fmt.Sprintf("[GET /ledger/vatType/{id}][%d] getLedgerVatTypeIdOK  %+v", 200, o.Payload)
}

func (o *GetLedgerVatTypeIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperVatType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
