// Code generated by go-swagger; DO NOT EDIT.

package vat_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetLedgerVatTypeReader is a Reader for the GetLedgerVatType structure.
type GetLedgerVatTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLedgerVatTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetLedgerVatTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLedgerVatTypeOK creates a GetLedgerVatTypeOK with default headers values
func NewGetLedgerVatTypeOK() *GetLedgerVatTypeOK {
	return &GetLedgerVatTypeOK{}
}

/*GetLedgerVatTypeOK handles this case with default header values.

successful operation
*/
type GetLedgerVatTypeOK struct {
	Payload *models.ListResponseVatType
}

func (o *GetLedgerVatTypeOK) Error() string {
	return fmt.Sprintf("[GET /ledger/vatType][%d] getLedgerVatTypeOK  %+v", 200, o.Payload)
}

func (o *GetLedgerVatTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseVatType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
