// Code generated by go-swagger; DO NOT EDIT.

package invoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInvoiceIDParams creates a new GetInvoiceIDParams object
// with the default values initialized.
func NewGetInvoiceIDParams() *GetInvoiceIDParams {
	var ()
	return &GetInvoiceIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInvoiceIDParamsWithTimeout creates a new GetInvoiceIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInvoiceIDParamsWithTimeout(timeout time.Duration) *GetInvoiceIDParams {
	var ()
	return &GetInvoiceIDParams{

		timeout: timeout,
	}
}

// NewGetInvoiceIDParamsWithContext creates a new GetInvoiceIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInvoiceIDParamsWithContext(ctx context.Context) *GetInvoiceIDParams {
	var ()
	return &GetInvoiceIDParams{

		Context: ctx,
	}
}

// NewGetInvoiceIDParamsWithHTTPClient creates a new GetInvoiceIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInvoiceIDParamsWithHTTPClient(client *http.Client) *GetInvoiceIDParams {
	var ()
	return &GetInvoiceIDParams{
		HTTPClient: client,
	}
}

/*GetInvoiceIDParams contains all the parameters to send to the API endpoint
for the get invoice ID operation typically these are written to a http.Request
*/
type GetInvoiceIDParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get invoice ID params
func (o *GetInvoiceIDParams) WithTimeout(timeout time.Duration) *GetInvoiceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get invoice ID params
func (o *GetInvoiceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get invoice ID params
func (o *GetInvoiceIDParams) WithContext(ctx context.Context) *GetInvoiceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get invoice ID params
func (o *GetInvoiceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get invoice ID params
func (o *GetInvoiceIDParams) WithHTTPClient(client *http.Client) *GetInvoiceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get invoice ID params
func (o *GetInvoiceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get invoice ID params
func (o *GetInvoiceIDParams) WithFields(fields *string) *GetInvoiceIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get invoice ID params
func (o *GetInvoiceIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the get invoice ID params
func (o *GetInvoiceIDParams) WithID(id int32) *GetInvoiceIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get invoice ID params
func (o *GetInvoiceIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetInvoiceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
