// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBankParams creates a new GetBankParams object
// with the default values initialized.
func NewGetBankParams() *GetBankParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetBankParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBankParamsWithTimeout creates a new GetBankParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBankParamsWithTimeout(timeout time.Duration) *GetBankParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetBankParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: timeout,
	}
}

// NewGetBankParamsWithContext creates a new GetBankParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBankParamsWithContext(ctx context.Context) *GetBankParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetBankParams{
		Count: &countDefault,
		From:  &fromDefault,

		Context: ctx,
	}
}

// NewGetBankParamsWithHTTPClient creates a new GetBankParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBankParamsWithHTTPClient(client *http.Client) *GetBankParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetBankParams{
		Count:      &countDefault,
		From:       &fromDefault,
		HTTPClient: client,
	}
}

/*GetBankParams contains all the parameters to send to the API endpoint
for the get bank operation typically these are written to a http.Request
*/
type GetBankParams struct {

	/*Count
	  Number of elements to return

	*/
	Count *int64
	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*From
	  From index

	*/
	From *int64
	/*ID
	  List of IDs

	*/
	ID *string
	/*RegisterNumbers
	  Bank register number (four digits)

	*/
	RegisterNumbers *string
	/*Sorting
	  Sorting pattern

	*/
	Sorting *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get bank params
func (o *GetBankParams) WithTimeout(timeout time.Duration) *GetBankParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bank params
func (o *GetBankParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bank params
func (o *GetBankParams) WithContext(ctx context.Context) *GetBankParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bank params
func (o *GetBankParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bank params
func (o *GetBankParams) WithHTTPClient(client *http.Client) *GetBankParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bank params
func (o *GetBankParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get bank params
func (o *GetBankParams) WithCount(count *int64) *GetBankParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get bank params
func (o *GetBankParams) SetCount(count *int64) {
	o.Count = count
}

// WithFields adds the fields to the get bank params
func (o *GetBankParams) WithFields(fields *string) *GetBankParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get bank params
func (o *GetBankParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFrom adds the from to the get bank params
func (o *GetBankParams) WithFrom(from *int64) *GetBankParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get bank params
func (o *GetBankParams) SetFrom(from *int64) {
	o.From = from
}

// WithID adds the id to the get bank params
func (o *GetBankParams) WithID(id *string) *GetBankParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get bank params
func (o *GetBankParams) SetID(id *string) {
	o.ID = id
}

// WithRegisterNumbers adds the registerNumbers to the get bank params
func (o *GetBankParams) WithRegisterNumbers(registerNumbers *string) *GetBankParams {
	o.SetRegisterNumbers(registerNumbers)
	return o
}

// SetRegisterNumbers adds the registerNumbers to the get bank params
func (o *GetBankParams) SetRegisterNumbers(registerNumbers *string) {
	o.RegisterNumbers = registerNumbers
}

// WithSorting adds the sorting to the get bank params
func (o *GetBankParams) WithSorting(sorting *string) *GetBankParams {
	o.SetSorting(sorting)
	return o
}

// SetSorting adds the sorting to the get bank params
func (o *GetBankParams) SetSorting(sorting *string) {
	o.Sorting = sorting
}

// WriteToRequest writes these params to a swagger request
func (o *GetBankParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.From != nil {

		// query param from
		var qrFrom int64
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := swag.FormatInt64(qrFrom)
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.RegisterNumbers != nil {

		// query param registerNumbers
		var qrRegisterNumbers string
		if o.RegisterNumbers != nil {
			qrRegisterNumbers = *o.RegisterNumbers
		}
		qRegisterNumbers := qrRegisterNumbers
		if qRegisterNumbers != "" {
			if err := r.SetQueryParam("registerNumbers", qRegisterNumbers); err != nil {
				return err
			}
		}

	}

	if o.Sorting != nil {

		// query param sorting
		var qrSorting string
		if o.Sorting != nil {
			qrSorting = *o.Sorting
		}
		qSorting := qrSorting
		if qSorting != "" {
			if err := r.SetQueryParam("sorting", qSorting); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
