// Code generated by go-swagger; DO NOT EDIT.

package department

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutDepartmentIDReader is a Reader for the PutDepartmentID structure.
type PutDepartmentIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDepartmentIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutDepartmentIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutDepartmentIDOK creates a PutDepartmentIDOK with default headers values
func NewPutDepartmentIDOK() *PutDepartmentIDOK {
	return &PutDepartmentIDOK{}
}

/*PutDepartmentIDOK handles this case with default header values.

successful operation
*/
type PutDepartmentIDOK struct {
	Payload *models.ResponseWrapperDepartment
}

func (o *PutDepartmentIDOK) Error() string {
	return fmt.Sprintf("[PUT /department/{id}][%d] putDepartmentIdOK  %+v", 200, o.Payload)
}

func (o *PutDepartmentIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperDepartment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
