// Code generated by go-swagger; DO NOT EDIT.

package rate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new rate API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for rate API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetTravelExpenseRate bs e t a find rates corresponding with sent data
*/
func (a *Client) GetTravelExpenseRate(params *GetTravelExpenseRateParams, authInfo runtime.ClientAuthInfoWriter) (*GetTravelExpenseRateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTravelExpenseRateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetTravelExpenseRate",
		Method:             "GET",
		PathPattern:        "/travelExpense/rate",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTravelExpenseRateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTravelExpenseRateOK), nil

}

/*
GetTravelExpenseRateID bs e t a get travel expense rate by ID
*/
func (a *Client) GetTravelExpenseRateID(params *GetTravelExpenseRateIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetTravelExpenseRateIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTravelExpenseRateIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetTravelExpenseRateID",
		Method:             "GET",
		PathPattern:        "/travelExpense/rate/{id}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTravelExpenseRateIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTravelExpenseRateIDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
