// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutOrderIDReader is a Reader for the PutOrderID structure.
type PutOrderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutOrderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutOrderIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutOrderIDOK creates a PutOrderIDOK with default headers values
func NewPutOrderIDOK() *PutOrderIDOK {
	return &PutOrderIDOK{}
}

/*PutOrderIDOK handles this case with default header values.

successful operation
*/
type PutOrderIDOK struct {
	Payload *models.ResponseWrapperOrder
}

func (o *PutOrderIDOK) Error() string {
	return fmt.Sprintf("[PUT /order/{id}][%d] putOrderIdOK  %+v", 200, o.Payload)
}

func (o *PutOrderIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperOrder)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
