// Code generated by go-swagger; DO NOT EDIT.

package mileage_allowance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteTravelExpenseMileageAllowanceIDReader is a Reader for the DeleteTravelExpenseMileageAllowanceID structure.
type DeleteTravelExpenseMileageAllowanceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTravelExpenseMileageAllowanceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteTravelExpenseMileageAllowanceIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteTravelExpenseMileageAllowanceIDDefault creates a DeleteTravelExpenseMileageAllowanceIDDefault with default headers values
func NewDeleteTravelExpenseMileageAllowanceIDDefault(code int) *DeleteTravelExpenseMileageAllowanceIDDefault {
	return &DeleteTravelExpenseMileageAllowanceIDDefault{
		_statusCode: code,
	}
}

/*DeleteTravelExpenseMileageAllowanceIDDefault handles this case with default header values.

successful operation
*/
type DeleteTravelExpenseMileageAllowanceIDDefault struct {
	_statusCode int
}

// Code gets the status code for the delete travel expense mileage allowance ID default response
func (o *DeleteTravelExpenseMileageAllowanceIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteTravelExpenseMileageAllowanceIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /travelExpense/mileageAllowance/{id}][%d] DeleteTravelExpenseMileageAllowanceID default ", o._statusCode)
}

func (o *DeleteTravelExpenseMileageAllowanceIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
