// Code generated by go-swagger; DO NOT EDIT.

package mileage_allowance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTravelExpenseMileageAllowanceIDParams creates a new GetTravelExpenseMileageAllowanceIDParams object
// with the default values initialized.
func NewGetTravelExpenseMileageAllowanceIDParams() *GetTravelExpenseMileageAllowanceIDParams {
	var ()
	return &GetTravelExpenseMileageAllowanceIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTravelExpenseMileageAllowanceIDParamsWithTimeout creates a new GetTravelExpenseMileageAllowanceIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTravelExpenseMileageAllowanceIDParamsWithTimeout(timeout time.Duration) *GetTravelExpenseMileageAllowanceIDParams {
	var ()
	return &GetTravelExpenseMileageAllowanceIDParams{

		timeout: timeout,
	}
}

// NewGetTravelExpenseMileageAllowanceIDParamsWithContext creates a new GetTravelExpenseMileageAllowanceIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTravelExpenseMileageAllowanceIDParamsWithContext(ctx context.Context) *GetTravelExpenseMileageAllowanceIDParams {
	var ()
	return &GetTravelExpenseMileageAllowanceIDParams{

		Context: ctx,
	}
}

// NewGetTravelExpenseMileageAllowanceIDParamsWithHTTPClient creates a new GetTravelExpenseMileageAllowanceIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTravelExpenseMileageAllowanceIDParamsWithHTTPClient(client *http.Client) *GetTravelExpenseMileageAllowanceIDParams {
	var ()
	return &GetTravelExpenseMileageAllowanceIDParams{
		HTTPClient: client,
	}
}

/*GetTravelExpenseMileageAllowanceIDParams contains all the parameters to send to the API endpoint
for the get travel expense mileage allowance ID operation typically these are written to a http.Request
*/
type GetTravelExpenseMileageAllowanceIDParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) WithTimeout(timeout time.Duration) *GetTravelExpenseMileageAllowanceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) WithContext(ctx context.Context) *GetTravelExpenseMileageAllowanceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) WithHTTPClient(client *http.Client) *GetTravelExpenseMileageAllowanceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) WithFields(fields *string) *GetTravelExpenseMileageAllowanceIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) WithID(id int32) *GetTravelExpenseMileageAllowanceIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get travel expense mileage allowance ID params
func (o *GetTravelExpenseMileageAllowanceIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetTravelExpenseMileageAllowanceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
