// Code generated by go-swagger; DO NOT EDIT.

package per_diem_compensation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPutTravelExpensePerDiemCompensationIDParams creates a new PutTravelExpensePerDiemCompensationIDParams object
// with the default values initialized.
func NewPutTravelExpensePerDiemCompensationIDParams() *PutTravelExpensePerDiemCompensationIDParams {
	var ()
	return &PutTravelExpensePerDiemCompensationIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutTravelExpensePerDiemCompensationIDParamsWithTimeout creates a new PutTravelExpensePerDiemCompensationIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutTravelExpensePerDiemCompensationIDParamsWithTimeout(timeout time.Duration) *PutTravelExpensePerDiemCompensationIDParams {
	var ()
	return &PutTravelExpensePerDiemCompensationIDParams{

		timeout: timeout,
	}
}

// NewPutTravelExpensePerDiemCompensationIDParamsWithContext creates a new PutTravelExpensePerDiemCompensationIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutTravelExpensePerDiemCompensationIDParamsWithContext(ctx context.Context) *PutTravelExpensePerDiemCompensationIDParams {
	var ()
	return &PutTravelExpensePerDiemCompensationIDParams{

		Context: ctx,
	}
}

// NewPutTravelExpensePerDiemCompensationIDParamsWithHTTPClient creates a new PutTravelExpensePerDiemCompensationIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutTravelExpensePerDiemCompensationIDParamsWithHTTPClient(client *http.Client) *PutTravelExpensePerDiemCompensationIDParams {
	var ()
	return &PutTravelExpensePerDiemCompensationIDParams{
		HTTPClient: client,
	}
}

/*PutTravelExpensePerDiemCompensationIDParams contains all the parameters to send to the API endpoint
for the put travel expense per diem compensation ID operation typically these are written to a http.Request
*/
type PutTravelExpensePerDiemCompensationIDParams struct {

	/*Body
	  Partial object describing what should be updated

	*/
	Body *models.PerDiemCompensation
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) WithTimeout(timeout time.Duration) *PutTravelExpensePerDiemCompensationIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) WithContext(ctx context.Context) *PutTravelExpensePerDiemCompensationIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) WithHTTPClient(client *http.Client) *PutTravelExpensePerDiemCompensationIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) WithBody(body *models.PerDiemCompensation) *PutTravelExpensePerDiemCompensationIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) SetBody(body *models.PerDiemCompensation) {
	o.Body = body
}

// WithID adds the id to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) WithID(id int32) *PutTravelExpensePerDiemCompensationIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put travel expense per diem compensation ID params
func (o *PutTravelExpensePerDiemCompensationIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTravelExpensePerDiemCompensationIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
