// Code generated by go-swagger; DO NOT EDIT.

package cost

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPostTravelExpenseCostParams creates a new PostTravelExpenseCostParams object
// with the default values initialized.
func NewPostTravelExpenseCostParams() *PostTravelExpenseCostParams {
	var ()
	return &PostTravelExpenseCostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTravelExpenseCostParamsWithTimeout creates a new PostTravelExpenseCostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTravelExpenseCostParamsWithTimeout(timeout time.Duration) *PostTravelExpenseCostParams {
	var ()
	return &PostTravelExpenseCostParams{

		timeout: timeout,
	}
}

// NewPostTravelExpenseCostParamsWithContext creates a new PostTravelExpenseCostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTravelExpenseCostParamsWithContext(ctx context.Context) *PostTravelExpenseCostParams {
	var ()
	return &PostTravelExpenseCostParams{

		Context: ctx,
	}
}

// NewPostTravelExpenseCostParamsWithHTTPClient creates a new PostTravelExpenseCostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTravelExpenseCostParamsWithHTTPClient(client *http.Client) *PostTravelExpenseCostParams {
	var ()
	return &PostTravelExpenseCostParams{
		HTTPClient: client,
	}
}

/*PostTravelExpenseCostParams contains all the parameters to send to the API endpoint
for the post travel expense cost operation typically these are written to a http.Request
*/
type PostTravelExpenseCostParams struct {

	/*Body
	  JSON representing the new object to be created. Should not have ID and version set.

	*/
	Body *models.Cost

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post travel expense cost params
func (o *PostTravelExpenseCostParams) WithTimeout(timeout time.Duration) *PostTravelExpenseCostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post travel expense cost params
func (o *PostTravelExpenseCostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post travel expense cost params
func (o *PostTravelExpenseCostParams) WithContext(ctx context.Context) *PostTravelExpenseCostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post travel expense cost params
func (o *PostTravelExpenseCostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post travel expense cost params
func (o *PostTravelExpenseCostParams) WithHTTPClient(client *http.Client) *PostTravelExpenseCostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post travel expense cost params
func (o *PostTravelExpenseCostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post travel expense cost params
func (o *PostTravelExpenseCostParams) WithBody(body *models.Cost) *PostTravelExpenseCostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post travel expense cost params
func (o *PostTravelExpenseCostParams) SetBody(body *models.Cost) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostTravelExpenseCostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
