// Code generated by go-swagger; DO NOT EDIT.

package cost

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPutTravelExpenseCostIDParams creates a new PutTravelExpenseCostIDParams object
// with the default values initialized.
func NewPutTravelExpenseCostIDParams() *PutTravelExpenseCostIDParams {
	var ()
	return &PutTravelExpenseCostIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutTravelExpenseCostIDParamsWithTimeout creates a new PutTravelExpenseCostIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutTravelExpenseCostIDParamsWithTimeout(timeout time.Duration) *PutTravelExpenseCostIDParams {
	var ()
	return &PutTravelExpenseCostIDParams{

		timeout: timeout,
	}
}

// NewPutTravelExpenseCostIDParamsWithContext creates a new PutTravelExpenseCostIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutTravelExpenseCostIDParamsWithContext(ctx context.Context) *PutTravelExpenseCostIDParams {
	var ()
	return &PutTravelExpenseCostIDParams{

		Context: ctx,
	}
}

// NewPutTravelExpenseCostIDParamsWithHTTPClient creates a new PutTravelExpenseCostIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutTravelExpenseCostIDParamsWithHTTPClient(client *http.Client) *PutTravelExpenseCostIDParams {
	var ()
	return &PutTravelExpenseCostIDParams{
		HTTPClient: client,
	}
}

/*PutTravelExpenseCostIDParams contains all the parameters to send to the API endpoint
for the put travel expense cost ID operation typically these are written to a http.Request
*/
type PutTravelExpenseCostIDParams struct {

	/*Body
	  Partial object describing what should be updated

	*/
	Body *models.Cost
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) WithTimeout(timeout time.Duration) *PutTravelExpenseCostIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) WithContext(ctx context.Context) *PutTravelExpenseCostIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) WithHTTPClient(client *http.Client) *PutTravelExpenseCostIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) WithBody(body *models.Cost) *PutTravelExpenseCostIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) SetBody(body *models.Cost) {
	o.Body = body
}

// WithID adds the id to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) WithID(id int32) *PutTravelExpenseCostIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put travel expense cost ID params
func (o *PutTravelExpenseCostIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTravelExpenseCostIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
