// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PostContactReader is a Reader for the PostContact structure.
type PostContactReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostContactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostContactCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostContactCreated creates a PostContactCreated with default headers values
func NewPostContactCreated() *PostContactCreated {
	return &PostContactCreated{}
}

/*PostContactCreated handles this case with default header values.

successfully created
*/
type PostContactCreated struct {
	Payload *models.ResponseWrapperContact
}

func (o *PostContactCreated) Error() string {
	return fmt.Sprintf("[POST /contact][%d] postContactCreated  %+v", 201, o.Payload)
}

func (o *PostContactCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperContact)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
