// Code generated by go-swagger; DO NOT EDIT.

package match

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteBankReconciliationMatchIDParams creates a new DeleteBankReconciliationMatchIDParams object
// with the default values initialized.
func NewDeleteBankReconciliationMatchIDParams() *DeleteBankReconciliationMatchIDParams {
	var ()
	return &DeleteBankReconciliationMatchIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBankReconciliationMatchIDParamsWithTimeout creates a new DeleteBankReconciliationMatchIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteBankReconciliationMatchIDParamsWithTimeout(timeout time.Duration) *DeleteBankReconciliationMatchIDParams {
	var ()
	return &DeleteBankReconciliationMatchIDParams{

		timeout: timeout,
	}
}

// NewDeleteBankReconciliationMatchIDParamsWithContext creates a new DeleteBankReconciliationMatchIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteBankReconciliationMatchIDParamsWithContext(ctx context.Context) *DeleteBankReconciliationMatchIDParams {
	var ()
	return &DeleteBankReconciliationMatchIDParams{

		Context: ctx,
	}
}

// NewDeleteBankReconciliationMatchIDParamsWithHTTPClient creates a new DeleteBankReconciliationMatchIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteBankReconciliationMatchIDParamsWithHTTPClient(client *http.Client) *DeleteBankReconciliationMatchIDParams {
	var ()
	return &DeleteBankReconciliationMatchIDParams{
		HTTPClient: client,
	}
}

/*DeleteBankReconciliationMatchIDParams contains all the parameters to send to the API endpoint
for the delete bank reconciliation match ID operation typically these are written to a http.Request
*/
type DeleteBankReconciliationMatchIDParams struct {

	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete bank reconciliation match ID params
func (o *DeleteBankReconciliationMatchIDParams) WithTimeout(timeout time.Duration) *DeleteBankReconciliationMatchIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete bank reconciliation match ID params
func (o *DeleteBankReconciliationMatchIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete bank reconciliation match ID params
func (o *DeleteBankReconciliationMatchIDParams) WithContext(ctx context.Context) *DeleteBankReconciliationMatchIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete bank reconciliation match ID params
func (o *DeleteBankReconciliationMatchIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete bank reconciliation match ID params
func (o *DeleteBankReconciliationMatchIDParams) WithHTTPClient(client *http.Client) *DeleteBankReconciliationMatchIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete bank reconciliation match ID params
func (o *DeleteBankReconciliationMatchIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete bank reconciliation match ID params
func (o *DeleteBankReconciliationMatchIDParams) WithID(id int32) *DeleteBankReconciliationMatchIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete bank reconciliation match ID params
func (o *DeleteBankReconciliationMatchIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBankReconciliationMatchIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
