// Code generated by go-swagger; DO NOT EDIT.

package entry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetTimesheetEntryIDReader is a Reader for the GetTimesheetEntryID structure.
type GetTimesheetEntryIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTimesheetEntryIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTimesheetEntryIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTimesheetEntryIDOK creates a GetTimesheetEntryIDOK with default headers values
func NewGetTimesheetEntryIDOK() *GetTimesheetEntryIDOK {
	return &GetTimesheetEntryIDOK{}
}

/*GetTimesheetEntryIDOK handles this case with default header values.

successful operation
*/
type GetTimesheetEntryIDOK struct {
	Payload *models.ResponseWrapperTimesheetEntry
}

func (o *GetTimesheetEntryIDOK) Error() string {
	return fmt.Sprintf("[GET /timesheet/entry/{id}][%d] getTimesheetEntryIdOK  %+v", 200, o.Payload)
}

func (o *GetTimesheetEntryIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperTimesheetEntry)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
