// Code generated by go-swagger; DO NOT EDIT.

package entry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPutTimesheetEntryListParams creates a new PutTimesheetEntryListParams object
// with the default values initialized.
func NewPutTimesheetEntryListParams() *PutTimesheetEntryListParams {
	var ()
	return &PutTimesheetEntryListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutTimesheetEntryListParamsWithTimeout creates a new PutTimesheetEntryListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutTimesheetEntryListParamsWithTimeout(timeout time.Duration) *PutTimesheetEntryListParams {
	var ()
	return &PutTimesheetEntryListParams{

		timeout: timeout,
	}
}

// NewPutTimesheetEntryListParamsWithContext creates a new PutTimesheetEntryListParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutTimesheetEntryListParamsWithContext(ctx context.Context) *PutTimesheetEntryListParams {
	var ()
	return &PutTimesheetEntryListParams{

		Context: ctx,
	}
}

// NewPutTimesheetEntryListParamsWithHTTPClient creates a new PutTimesheetEntryListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutTimesheetEntryListParamsWithHTTPClient(client *http.Client) *PutTimesheetEntryListParams {
	var ()
	return &PutTimesheetEntryListParams{
		HTTPClient: client,
	}
}

/*PutTimesheetEntryListParams contains all the parameters to send to the API endpoint
for the put timesheet entry list operation typically these are written to a http.Request
*/
type PutTimesheetEntryListParams struct {

	/*Body
	  List of timesheet entry objects to update

	*/
	Body []*models.TimesheetEntry

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put timesheet entry list params
func (o *PutTimesheetEntryListParams) WithTimeout(timeout time.Duration) *PutTimesheetEntryListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put timesheet entry list params
func (o *PutTimesheetEntryListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put timesheet entry list params
func (o *PutTimesheetEntryListParams) WithContext(ctx context.Context) *PutTimesheetEntryListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put timesheet entry list params
func (o *PutTimesheetEntryListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put timesheet entry list params
func (o *PutTimesheetEntryListParams) WithHTTPClient(client *http.Client) *PutTimesheetEntryListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put timesheet entry list params
func (o *PutTimesheetEntryListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put timesheet entry list params
func (o *PutTimesheetEntryListParams) WithBody(body []*models.TimesheetEntry) *PutTimesheetEntryListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put timesheet entry list params
func (o *PutTimesheetEntryListParams) SetBody(body []*models.TimesheetEntry) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PutTimesheetEntryListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
