// Code generated by go-swagger; DO NOT EDIT.

package entry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutTimesheetEntryListReader is a Reader for the PutTimesheetEntryList structure.
type PutTimesheetEntryListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTimesheetEntryListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutTimesheetEntryListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutTimesheetEntryListOK creates a PutTimesheetEntryListOK with default headers values
func NewPutTimesheetEntryListOK() *PutTimesheetEntryListOK {
	return &PutTimesheetEntryListOK{}
}

/*PutTimesheetEntryListOK handles this case with default header values.

successful operation
*/
type PutTimesheetEntryListOK struct {
	Payload *models.ListResponseTimesheetEntry
}

func (o *PutTimesheetEntryListOK) Error() string {
	return fmt.Sprintf("[PUT /timesheet/entry/list][%d] putTimesheetEntryListOK  %+v", 200, o.Payload)
}

func (o *PutTimesheetEntryListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseTimesheetEntry)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
