// Code generated by go-swagger; DO NOT EDIT.

package entry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutTimesheetEntryIDReader is a Reader for the PutTimesheetEntryID structure.
type PutTimesheetEntryIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTimesheetEntryIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutTimesheetEntryIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutTimesheetEntryIDOK creates a PutTimesheetEntryIDOK with default headers values
func NewPutTimesheetEntryIDOK() *PutTimesheetEntryIDOK {
	return &PutTimesheetEntryIDOK{}
}

/*PutTimesheetEntryIDOK handles this case with default header values.

successful operation
*/
type PutTimesheetEntryIDOK struct {
	Payload *models.ResponseWrapperTimesheetEntry
}

func (o *PutTimesheetEntryIDOK) Error() string {
	return fmt.Sprintf("[PUT /timesheet/entry/{id}][%d] putTimesheetEntryIdOK  %+v", 200, o.Payload)
}

func (o *PutTimesheetEntryIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperTimesheetEntry)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
