// Code generated by go-swagger; DO NOT EDIT.

package ledger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetLedgerOpenPostReader is a Reader for the GetLedgerOpenPost structure.
type GetLedgerOpenPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLedgerOpenPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetLedgerOpenPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLedgerOpenPostOK creates a GetLedgerOpenPostOK with default headers values
func NewGetLedgerOpenPostOK() *GetLedgerOpenPostOK {
	return &GetLedgerOpenPostOK{}
}

/*GetLedgerOpenPostOK handles this case with default header values.

successful operation
*/
type GetLedgerOpenPostOK struct {
	Payload *models.ListResponseLedgerAccount
}

func (o *GetLedgerOpenPostOK) Error() string {
	return fmt.Sprintf("[GET /ledger/openPost][%d] getLedgerOpenPostOK  %+v", 200, o.Payload)
}

func (o *GetLedgerOpenPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseLedgerAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
