// Code generated by go-swagger; DO NOT EDIT.

package ledger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLedgerParams creates a new GetLedgerParams object
// with the default values initialized.
func NewGetLedgerParams() *GetLedgerParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetLedgerParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLedgerParamsWithTimeout creates a new GetLedgerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLedgerParamsWithTimeout(timeout time.Duration) *GetLedgerParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetLedgerParams{
		Count: &countDefault,
		From:  &fromDefault,

		timeout: timeout,
	}
}

// NewGetLedgerParamsWithContext creates a new GetLedgerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLedgerParamsWithContext(ctx context.Context) *GetLedgerParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetLedgerParams{
		Count: &countDefault,
		From:  &fromDefault,

		Context: ctx,
	}
}

// NewGetLedgerParamsWithHTTPClient creates a new GetLedgerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLedgerParamsWithHTTPClient(client *http.Client) *GetLedgerParams {
	var (
		countDefault = int64(1000)
		fromDefault  = int64(0)
	)
	return &GetLedgerParams{
		Count:      &countDefault,
		From:       &fromDefault,
		HTTPClient: client,
	}
}

/*GetLedgerParams contains all the parameters to send to the API endpoint
for the get ledger operation typically these are written to a http.Request
*/
type GetLedgerParams struct {

	/*AccountID
	  Element ID

	*/
	AccountID *int32
	/*Count
	  Number of elements to return

	*/
	Count *int64
	/*CustomerID
	  Element ID

	*/
	CustomerID *int32
	/*DateFrom
	  Format is yyyy-MM-dd (from and incl.).

	*/
	DateFrom string
	/*DateTo
	  Format is yyyy-MM-dd (to and excl.).

	*/
	DateTo string
	/*DepartmentID
	  Element ID

	*/
	DepartmentID *int32
	/*EmployeeID
	  Element ID

	*/
	EmployeeID *int32
	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*From
	  From index

	*/
	From *int64
	/*OpenPostings
	  Deprecated

	*/
	OpenPostings *string
	/*ProductID
	  Element ID

	*/
	ProductID *int32
	/*ProjectID
	  Element ID

	*/
	ProjectID *int32
	/*Sorting
	  Sorting pattern

	*/
	Sorting *string
	/*SupplierID
	  Element ID

	*/
	SupplierID *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get ledger params
func (o *GetLedgerParams) WithTimeout(timeout time.Duration) *GetLedgerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ledger params
func (o *GetLedgerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ledger params
func (o *GetLedgerParams) WithContext(ctx context.Context) *GetLedgerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ledger params
func (o *GetLedgerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ledger params
func (o *GetLedgerParams) WithHTTPClient(client *http.Client) *GetLedgerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ledger params
func (o *GetLedgerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get ledger params
func (o *GetLedgerParams) WithAccountID(accountID *int32) *GetLedgerParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get ledger params
func (o *GetLedgerParams) SetAccountID(accountID *int32) {
	o.AccountID = accountID
}

// WithCount adds the count to the get ledger params
func (o *GetLedgerParams) WithCount(count *int64) *GetLedgerParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get ledger params
func (o *GetLedgerParams) SetCount(count *int64) {
	o.Count = count
}

// WithCustomerID adds the customerID to the get ledger params
func (o *GetLedgerParams) WithCustomerID(customerID *int32) *GetLedgerParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get ledger params
func (o *GetLedgerParams) SetCustomerID(customerID *int32) {
	o.CustomerID = customerID
}

// WithDateFrom adds the dateFrom to the get ledger params
func (o *GetLedgerParams) WithDateFrom(dateFrom string) *GetLedgerParams {
	o.SetDateFrom(dateFrom)
	return o
}

// SetDateFrom adds the dateFrom to the get ledger params
func (o *GetLedgerParams) SetDateFrom(dateFrom string) {
	o.DateFrom = dateFrom
}

// WithDateTo adds the dateTo to the get ledger params
func (o *GetLedgerParams) WithDateTo(dateTo string) *GetLedgerParams {
	o.SetDateTo(dateTo)
	return o
}

// SetDateTo adds the dateTo to the get ledger params
func (o *GetLedgerParams) SetDateTo(dateTo string) {
	o.DateTo = dateTo
}

// WithDepartmentID adds the departmentID to the get ledger params
func (o *GetLedgerParams) WithDepartmentID(departmentID *int32) *GetLedgerParams {
	o.SetDepartmentID(departmentID)
	return o
}

// SetDepartmentID adds the departmentId to the get ledger params
func (o *GetLedgerParams) SetDepartmentID(departmentID *int32) {
	o.DepartmentID = departmentID
}

// WithEmployeeID adds the employeeID to the get ledger params
func (o *GetLedgerParams) WithEmployeeID(employeeID *int32) *GetLedgerParams {
	o.SetEmployeeID(employeeID)
	return o
}

// SetEmployeeID adds the employeeId to the get ledger params
func (o *GetLedgerParams) SetEmployeeID(employeeID *int32) {
	o.EmployeeID = employeeID
}

// WithFields adds the fields to the get ledger params
func (o *GetLedgerParams) WithFields(fields *string) *GetLedgerParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get ledger params
func (o *GetLedgerParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFrom adds the from to the get ledger params
func (o *GetLedgerParams) WithFrom(from *int64) *GetLedgerParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get ledger params
func (o *GetLedgerParams) SetFrom(from *int64) {
	o.From = from
}

// WithOpenPostings adds the openPostings to the get ledger params
func (o *GetLedgerParams) WithOpenPostings(openPostings *string) *GetLedgerParams {
	o.SetOpenPostings(openPostings)
	return o
}

// SetOpenPostings adds the openPostings to the get ledger params
func (o *GetLedgerParams) SetOpenPostings(openPostings *string) {
	o.OpenPostings = openPostings
}

// WithProductID adds the productID to the get ledger params
func (o *GetLedgerParams) WithProductID(productID *int32) *GetLedgerParams {
	o.SetProductID(productID)
	return o
}

// SetProductID adds the productId to the get ledger params
func (o *GetLedgerParams) SetProductID(productID *int32) {
	o.ProductID = productID
}

// WithProjectID adds the projectID to the get ledger params
func (o *GetLedgerParams) WithProjectID(projectID *int32) *GetLedgerParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get ledger params
func (o *GetLedgerParams) SetProjectID(projectID *int32) {
	o.ProjectID = projectID
}

// WithSorting adds the sorting to the get ledger params
func (o *GetLedgerParams) WithSorting(sorting *string) *GetLedgerParams {
	o.SetSorting(sorting)
	return o
}

// SetSorting adds the sorting to the get ledger params
func (o *GetLedgerParams) SetSorting(sorting *string) {
	o.Sorting = sorting
}

// WithSupplierID adds the supplierID to the get ledger params
func (o *GetLedgerParams) WithSupplierID(supplierID *int32) *GetLedgerParams {
	o.SetSupplierID(supplierID)
	return o
}

// SetSupplierID adds the supplierId to the get ledger params
func (o *GetLedgerParams) SetSupplierID(supplierID *int32) {
	o.SupplierID = supplierID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLedgerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccountID != nil {

		// query param accountId
		var qrAccountID int32
		if o.AccountID != nil {
			qrAccountID = *o.AccountID
		}
		qAccountID := swag.FormatInt32(qrAccountID)
		if qAccountID != "" {
			if err := r.SetQueryParam("accountId", qAccountID); err != nil {
				return err
			}
		}

	}

	if o.Count != nil {

		// query param count
		var qrCount int64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.CustomerID != nil {

		// query param customerId
		var qrCustomerID int32
		if o.CustomerID != nil {
			qrCustomerID = *o.CustomerID
		}
		qCustomerID := swag.FormatInt32(qrCustomerID)
		if qCustomerID != "" {
			if err := r.SetQueryParam("customerId", qCustomerID); err != nil {
				return err
			}
		}

	}

	// query param dateFrom
	qrDateFrom := o.DateFrom
	qDateFrom := qrDateFrom
	if qDateFrom != "" {
		if err := r.SetQueryParam("dateFrom", qDateFrom); err != nil {
			return err
		}
	}

	// query param dateTo
	qrDateTo := o.DateTo
	qDateTo := qrDateTo
	if qDateTo != "" {
		if err := r.SetQueryParam("dateTo", qDateTo); err != nil {
			return err
		}
	}

	if o.DepartmentID != nil {

		// query param departmentId
		var qrDepartmentID int32
		if o.DepartmentID != nil {
			qrDepartmentID = *o.DepartmentID
		}
		qDepartmentID := swag.FormatInt32(qrDepartmentID)
		if qDepartmentID != "" {
			if err := r.SetQueryParam("departmentId", qDepartmentID); err != nil {
				return err
			}
		}

	}

	if o.EmployeeID != nil {

		// query param employeeId
		var qrEmployeeID int32
		if o.EmployeeID != nil {
			qrEmployeeID = *o.EmployeeID
		}
		qEmployeeID := swag.FormatInt32(qrEmployeeID)
		if qEmployeeID != "" {
			if err := r.SetQueryParam("employeeId", qEmployeeID); err != nil {
				return err
			}
		}

	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.From != nil {

		// query param from
		var qrFrom int64
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := swag.FormatInt64(qrFrom)
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	if o.OpenPostings != nil {

		// query param openPostings
		var qrOpenPostings string
		if o.OpenPostings != nil {
			qrOpenPostings = *o.OpenPostings
		}
		qOpenPostings := qrOpenPostings
		if qOpenPostings != "" {
			if err := r.SetQueryParam("openPostings", qOpenPostings); err != nil {
				return err
			}
		}

	}

	if o.ProductID != nil {

		// query param productId
		var qrProductID int32
		if o.ProductID != nil {
			qrProductID = *o.ProductID
		}
		qProductID := swag.FormatInt32(qrProductID)
		if qProductID != "" {
			if err := r.SetQueryParam("productId", qProductID); err != nil {
				return err
			}
		}

	}

	if o.ProjectID != nil {

		// query param projectId
		var qrProjectID int32
		if o.ProjectID != nil {
			qrProjectID = *o.ProjectID
		}
		qProjectID := swag.FormatInt32(qrProjectID)
		if qProjectID != "" {
			if err := r.SetQueryParam("projectId", qProjectID); err != nil {
				return err
			}
		}

	}

	if o.Sorting != nil {

		// query param sorting
		var qrSorting string
		if o.Sorting != nil {
			qrSorting = *o.Sorting
		}
		qSorting := qrSorting
		if qSorting != "" {
			if err := r.SetQueryParam("sorting", qSorting); err != nil {
				return err
			}
		}

	}

	if o.SupplierID != nil {

		// query param supplierId
		var qrSupplierID int32
		if o.SupplierID != nil {
			qrSupplierID = *o.SupplierID
		}
		qSupplierID := swag.FormatInt32(qrSupplierID)
		if qSupplierID != "" {
			if err := r.SetQueryParam("supplierId", qSupplierID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
