// Code generated by go-swagger; DO NOT EDIT.

package voucher_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new voucher type API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for voucher type API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetLedgerVoucherType finds voucher types corresponding with sent data
*/
func (a *Client) GetLedgerVoucherType(params *GetLedgerVoucherTypeParams, authInfo runtime.ClientAuthInfoWriter) (*GetLedgerVoucherTypeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLedgerVoucherTypeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetLedgerVoucherType",
		Method:             "GET",
		PathPattern:        "/ledger/voucherType",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLedgerVoucherTypeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetLedgerVoucherTypeOK), nil

}

/*
GetLedgerVoucherTypeID gets voucher type by ID
*/
func (a *Client) GetLedgerVoucherTypeID(params *GetLedgerVoucherTypeIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetLedgerVoucherTypeIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLedgerVoucherTypeIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetLedgerVoucherTypeID",
		Method:             "GET",
		PathPattern:        "/ledger/voucherType/{id}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLedgerVoucherTypeIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetLedgerVoucherTypeIDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
