// Code generated by go-swagger; DO NOT EDIT.

package accommodation_allowance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPutTravelExpenseAccommodationAllowanceIDParams creates a new PutTravelExpenseAccommodationAllowanceIDParams object
// with the default values initialized.
func NewPutTravelExpenseAccommodationAllowanceIDParams() *PutTravelExpenseAccommodationAllowanceIDParams {
	var ()
	return &PutTravelExpenseAccommodationAllowanceIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutTravelExpenseAccommodationAllowanceIDParamsWithTimeout creates a new PutTravelExpenseAccommodationAllowanceIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutTravelExpenseAccommodationAllowanceIDParamsWithTimeout(timeout time.Duration) *PutTravelExpenseAccommodationAllowanceIDParams {
	var ()
	return &PutTravelExpenseAccommodationAllowanceIDParams{

		timeout: timeout,
	}
}

// NewPutTravelExpenseAccommodationAllowanceIDParamsWithContext creates a new PutTravelExpenseAccommodationAllowanceIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutTravelExpenseAccommodationAllowanceIDParamsWithContext(ctx context.Context) *PutTravelExpenseAccommodationAllowanceIDParams {
	var ()
	return &PutTravelExpenseAccommodationAllowanceIDParams{

		Context: ctx,
	}
}

// NewPutTravelExpenseAccommodationAllowanceIDParamsWithHTTPClient creates a new PutTravelExpenseAccommodationAllowanceIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutTravelExpenseAccommodationAllowanceIDParamsWithHTTPClient(client *http.Client) *PutTravelExpenseAccommodationAllowanceIDParams {
	var ()
	return &PutTravelExpenseAccommodationAllowanceIDParams{
		HTTPClient: client,
	}
}

/*PutTravelExpenseAccommodationAllowanceIDParams contains all the parameters to send to the API endpoint
for the put travel expense accommodation allowance ID operation typically these are written to a http.Request
*/
type PutTravelExpenseAccommodationAllowanceIDParams struct {

	/*Body
	  Partial object describing what should be updated

	*/
	Body *models.AccommodationAllowance
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) WithTimeout(timeout time.Duration) *PutTravelExpenseAccommodationAllowanceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) WithContext(ctx context.Context) *PutTravelExpenseAccommodationAllowanceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) WithHTTPClient(client *http.Client) *PutTravelExpenseAccommodationAllowanceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) WithBody(body *models.AccommodationAllowance) *PutTravelExpenseAccommodationAllowanceIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) SetBody(body *models.AccommodationAllowance) {
	o.Body = body
}

// WithID adds the id to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) WithID(id int32) *PutTravelExpenseAccommodationAllowanceIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put travel expense accommodation allowance ID params
func (o *PutTravelExpenseAccommodationAllowanceIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTravelExpenseAccommodationAllowanceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
