// Code generated by go-swagger; DO NOT EDIT.

package holiday

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSalarySettingsHolidayListReader is a Reader for the DeleteSalarySettingsHolidayList structure.
type DeleteSalarySettingsHolidayListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSalarySettingsHolidayListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteSalarySettingsHolidayListDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteSalarySettingsHolidayListDefault creates a DeleteSalarySettingsHolidayListDefault with default headers values
func NewDeleteSalarySettingsHolidayListDefault(code int) *DeleteSalarySettingsHolidayListDefault {
	return &DeleteSalarySettingsHolidayListDefault{
		_statusCode: code,
	}
}

/*DeleteSalarySettingsHolidayListDefault handles this case with default header values.

successful operation
*/
type DeleteSalarySettingsHolidayListDefault struct {
	_statusCode int
}

// Code gets the status code for the delete salary settings holiday list default response
func (o *DeleteSalarySettingsHolidayListDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSalarySettingsHolidayListDefault) Error() string {
	return fmt.Sprintf("[DELETE /salary/settings/holiday/list][%d] DeleteSalarySettingsHolidayList default ", o._statusCode)
}

func (o *DeleteSalarySettingsHolidayListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
