// Code generated by go-swagger; DO NOT EDIT.

package holiday

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutSalarySettingsHolidayListReader is a Reader for the PutSalarySettingsHolidayList structure.
type PutSalarySettingsHolidayListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutSalarySettingsHolidayListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutSalarySettingsHolidayListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutSalarySettingsHolidayListOK creates a PutSalarySettingsHolidayListOK with default headers values
func NewPutSalarySettingsHolidayListOK() *PutSalarySettingsHolidayListOK {
	return &PutSalarySettingsHolidayListOK{}
}

/*PutSalarySettingsHolidayListOK handles this case with default header values.

successful operation
*/
type PutSalarySettingsHolidayListOK struct {
	Payload *models.ListResponseCompanyHoliday
}

func (o *PutSalarySettingsHolidayListOK) Error() string {
	return fmt.Sprintf("[PUT /salary/settings/holiday/list][%d] putSalarySettingsHolidayListOK  %+v", 200, o.Payload)
}

func (o *PutSalarySettingsHolidayListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseCompanyHoliday)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
