// Code generated by go-swagger; DO NOT EDIT.

package time_clock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTimesheetTimeClockIDParams creates a new GetTimesheetTimeClockIDParams object
// with the default values initialized.
func NewGetTimesheetTimeClockIDParams() *GetTimesheetTimeClockIDParams {
	var ()
	return &GetTimesheetTimeClockIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTimesheetTimeClockIDParamsWithTimeout creates a new GetTimesheetTimeClockIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTimesheetTimeClockIDParamsWithTimeout(timeout time.Duration) *GetTimesheetTimeClockIDParams {
	var ()
	return &GetTimesheetTimeClockIDParams{

		timeout: timeout,
	}
}

// NewGetTimesheetTimeClockIDParamsWithContext creates a new GetTimesheetTimeClockIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTimesheetTimeClockIDParamsWithContext(ctx context.Context) *GetTimesheetTimeClockIDParams {
	var ()
	return &GetTimesheetTimeClockIDParams{

		Context: ctx,
	}
}

// NewGetTimesheetTimeClockIDParamsWithHTTPClient creates a new GetTimesheetTimeClockIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTimesheetTimeClockIDParamsWithHTTPClient(client *http.Client) *GetTimesheetTimeClockIDParams {
	var ()
	return &GetTimesheetTimeClockIDParams{
		HTTPClient: client,
	}
}

/*GetTimesheetTimeClockIDParams contains all the parameters to send to the API endpoint
for the get timesheet time clock ID operation typically these are written to a http.Request
*/
type GetTimesheetTimeClockIDParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) WithTimeout(timeout time.Duration) *GetTimesheetTimeClockIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) WithContext(ctx context.Context) *GetTimesheetTimeClockIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) WithHTTPClient(client *http.Client) *GetTimesheetTimeClockIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) WithFields(fields *string) *GetTimesheetTimeClockIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) WithID(id int32) *GetTimesheetTimeClockIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get timesheet time clock ID params
func (o *GetTimesheetTimeClockIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetTimesheetTimeClockIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
