// Code generated by go-swagger; DO NOT EDIT.

package time_clock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutTimesheetTimeClockIDReader is a Reader for the PutTimesheetTimeClockID structure.
type PutTimesheetTimeClockIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTimesheetTimeClockIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutTimesheetTimeClockIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutTimesheetTimeClockIDOK creates a PutTimesheetTimeClockIDOK with default headers values
func NewPutTimesheetTimeClockIDOK() *PutTimesheetTimeClockIDOK {
	return &PutTimesheetTimeClockIDOK{}
}

/*PutTimesheetTimeClockIDOK handles this case with default header values.

successful operation
*/
type PutTimesheetTimeClockIDOK struct {
	Payload *models.ResponseWrapperTimeClock
}

func (o *PutTimesheetTimeClockIDOK) Error() string {
	return fmt.Sprintf("[PUT /timesheet/timeClock/{id}][%d] putTimesheetTimeClockIdOK  %+v", 200, o.Payload)
}

func (o *PutTimesheetTimeClockIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperTimeClock)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
