// Code generated by go-swagger; DO NOT EDIT.

package reconciliation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetBankReconciliationLastClosedReader is a Reader for the GetBankReconciliationLastClosed structure.
type GetBankReconciliationLastClosedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBankReconciliationLastClosedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetBankReconciliationLastClosedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBankReconciliationLastClosedOK creates a GetBankReconciliationLastClosedOK with default headers values
func NewGetBankReconciliationLastClosedOK() *GetBankReconciliationLastClosedOK {
	return &GetBankReconciliationLastClosedOK{}
}

/*GetBankReconciliationLastClosedOK handles this case with default header values.

successful operation
*/
type GetBankReconciliationLastClosedOK struct {
	Payload *models.ResponseWrapperBankReconciliation
}

func (o *GetBankReconciliationLastClosedOK) Error() string {
	return fmt.Sprintf("[GET /bank/reconciliation/lastClosed][%d] getBankReconciliationLastClosedOK  %+v", 200, o.Payload)
}

func (o *GetBankReconciliationLastClosedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperBankReconciliation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
