// Code generated by go-swagger; DO NOT EDIT.

package reconciliation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetBankReconciliationIDReader is a Reader for the GetBankReconciliationID structure.
type GetBankReconciliationIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBankReconciliationIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetBankReconciliationIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBankReconciliationIDOK creates a GetBankReconciliationIDOK with default headers values
func NewGetBankReconciliationIDOK() *GetBankReconciliationIDOK {
	return &GetBankReconciliationIDOK{}
}

/*GetBankReconciliationIDOK handles this case with default header values.

successful operation
*/
type GetBankReconciliationIDOK struct {
	Payload *models.ResponseWrapperBankReconciliation
}

func (o *GetBankReconciliationIDOK) Error() string {
	return fmt.Sprintf("[GET /bank/reconciliation/{id}][%d] getBankReconciliationIdOK  %+v", 200, o.Payload)
}

func (o *GetBankReconciliationIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperBankReconciliation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
