// Code generated by go-swagger; DO NOT EDIT.

package reconciliation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPostBankReconciliationParams creates a new PostBankReconciliationParams object
// with the default values initialized.
func NewPostBankReconciliationParams() *PostBankReconciliationParams {
	var ()
	return &PostBankReconciliationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostBankReconciliationParamsWithTimeout creates a new PostBankReconciliationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostBankReconciliationParamsWithTimeout(timeout time.Duration) *PostBankReconciliationParams {
	var ()
	return &PostBankReconciliationParams{

		timeout: timeout,
	}
}

// NewPostBankReconciliationParamsWithContext creates a new PostBankReconciliationParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostBankReconciliationParamsWithContext(ctx context.Context) *PostBankReconciliationParams {
	var ()
	return &PostBankReconciliationParams{

		Context: ctx,
	}
}

// NewPostBankReconciliationParamsWithHTTPClient creates a new PostBankReconciliationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostBankReconciliationParamsWithHTTPClient(client *http.Client) *PostBankReconciliationParams {
	var ()
	return &PostBankReconciliationParams{
		HTTPClient: client,
	}
}

/*PostBankReconciliationParams contains all the parameters to send to the API endpoint
for the post bank reconciliation operation typically these are written to a http.Request
*/
type PostBankReconciliationParams struct {

	/*Body
	  JSON representing the new object to be created. Should not have ID and version set.

	*/
	Body *models.BankReconciliation

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post bank reconciliation params
func (o *PostBankReconciliationParams) WithTimeout(timeout time.Duration) *PostBankReconciliationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post bank reconciliation params
func (o *PostBankReconciliationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post bank reconciliation params
func (o *PostBankReconciliationParams) WithContext(ctx context.Context) *PostBankReconciliationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post bank reconciliation params
func (o *PostBankReconciliationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post bank reconciliation params
func (o *PostBankReconciliationParams) WithHTTPClient(client *http.Client) *PostBankReconciliationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post bank reconciliation params
func (o *PostBankReconciliationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post bank reconciliation params
func (o *PostBankReconciliationParams) WithBody(body *models.BankReconciliation) *PostBankReconciliationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post bank reconciliation params
func (o *PostBankReconciliationParams) SetBody(body *models.BankReconciliation) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostBankReconciliationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
