// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBankStatementTransactionIDParams creates a new GetBankStatementTransactionIDParams object
// with the default values initialized.
func NewGetBankStatementTransactionIDParams() *GetBankStatementTransactionIDParams {
	var ()
	return &GetBankStatementTransactionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBankStatementTransactionIDParamsWithTimeout creates a new GetBankStatementTransactionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBankStatementTransactionIDParamsWithTimeout(timeout time.Duration) *GetBankStatementTransactionIDParams {
	var ()
	return &GetBankStatementTransactionIDParams{

		timeout: timeout,
	}
}

// NewGetBankStatementTransactionIDParamsWithContext creates a new GetBankStatementTransactionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBankStatementTransactionIDParamsWithContext(ctx context.Context) *GetBankStatementTransactionIDParams {
	var ()
	return &GetBankStatementTransactionIDParams{

		Context: ctx,
	}
}

// NewGetBankStatementTransactionIDParamsWithHTTPClient creates a new GetBankStatementTransactionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBankStatementTransactionIDParamsWithHTTPClient(client *http.Client) *GetBankStatementTransactionIDParams {
	var ()
	return &GetBankStatementTransactionIDParams{
		HTTPClient: client,
	}
}

/*GetBankStatementTransactionIDParams contains all the parameters to send to the API endpoint
for the get bank statement transaction ID operation typically these are written to a http.Request
*/
type GetBankStatementTransactionIDParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) WithTimeout(timeout time.Duration) *GetBankStatementTransactionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) WithContext(ctx context.Context) *GetBankStatementTransactionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) WithHTTPClient(client *http.Client) *GetBankStatementTransactionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) WithFields(fields *string) *GetBankStatementTransactionIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) WithID(id int32) *GetBankStatementTransactionIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get bank statement transaction ID params
func (o *GetBankStatementTransactionIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBankStatementTransactionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
