// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetBankStatementTransactionReader is a Reader for the GetBankStatementTransaction structure.
type GetBankStatementTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBankStatementTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetBankStatementTransactionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBankStatementTransactionOK creates a GetBankStatementTransactionOK with default headers values
func NewGetBankStatementTransactionOK() *GetBankStatementTransactionOK {
	return &GetBankStatementTransactionOK{}
}

/*GetBankStatementTransactionOK handles this case with default header values.

successful operation
*/
type GetBankStatementTransactionOK struct {
	Payload *models.ListResponseBankTransaction
}

func (o *GetBankStatementTransactionOK) Error() string {
	return fmt.Sprintf("[GET /bank/statement/transaction][%d] getBankStatementTransactionOK  %+v", 200, o.Payload)
}

func (o *GetBankStatementTransactionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseBankTransaction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
