// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetBankStatementTransactionIDReader is a Reader for the GetBankStatementTransactionID structure.
type GetBankStatementTransactionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBankStatementTransactionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetBankStatementTransactionIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBankStatementTransactionIDOK creates a GetBankStatementTransactionIDOK with default headers values
func NewGetBankStatementTransactionIDOK() *GetBankStatementTransactionIDOK {
	return &GetBankStatementTransactionIDOK{}
}

/*GetBankStatementTransactionIDOK handles this case with default header values.

successful operation
*/
type GetBankStatementTransactionIDOK struct {
	Payload *models.ResponseWrapperBankTransaction
}

func (o *GetBankStatementTransactionIDOK) Error() string {
	return fmt.Sprintf("[GET /bank/statement/transaction/{id}][%d] getBankStatementTransactionIdOK  %+v", 200, o.Payload)
}

func (o *GetBankStatementTransactionIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperBankTransaction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
