// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPostSalaryTransactionParams creates a new PostSalaryTransactionParams object
// with the default values initialized.
func NewPostSalaryTransactionParams() *PostSalaryTransactionParams {
	var (
		generateTaxDeductionDefault = bool(false)
	)
	return &PostSalaryTransactionParams{
		GenerateTaxDeduction: &generateTaxDeductionDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSalaryTransactionParamsWithTimeout creates a new PostSalaryTransactionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSalaryTransactionParamsWithTimeout(timeout time.Duration) *PostSalaryTransactionParams {
	var (
		generateTaxDeductionDefault = bool(false)
	)
	return &PostSalaryTransactionParams{
		GenerateTaxDeduction: &generateTaxDeductionDefault,

		timeout: timeout,
	}
}

// NewPostSalaryTransactionParamsWithContext creates a new PostSalaryTransactionParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSalaryTransactionParamsWithContext(ctx context.Context) *PostSalaryTransactionParams {
	var (
		generateTaxDeductionDefault = bool(false)
	)
	return &PostSalaryTransactionParams{
		GenerateTaxDeduction: &generateTaxDeductionDefault,

		Context: ctx,
	}
}

// NewPostSalaryTransactionParamsWithHTTPClient creates a new PostSalaryTransactionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSalaryTransactionParamsWithHTTPClient(client *http.Client) *PostSalaryTransactionParams {
	var (
		generateTaxDeductionDefault = bool(false)
	)
	return &PostSalaryTransactionParams{
		GenerateTaxDeduction: &generateTaxDeductionDefault,
		HTTPClient:           client,
	}
}

/*PostSalaryTransactionParams contains all the parameters to send to the API endpoint
for the post salary transaction operation typically these are written to a http.Request
*/
type PostSalaryTransactionParams struct {

	/*Body
	  JSON representing the new object to be created. Should not have ID and version set.

	*/
	Body *models.SalaryTransaction
	/*GenerateTaxDeduction
	  Generate tax deduction

	*/
	GenerateTaxDeduction *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post salary transaction params
func (o *PostSalaryTransactionParams) WithTimeout(timeout time.Duration) *PostSalaryTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post salary transaction params
func (o *PostSalaryTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post salary transaction params
func (o *PostSalaryTransactionParams) WithContext(ctx context.Context) *PostSalaryTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post salary transaction params
func (o *PostSalaryTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post salary transaction params
func (o *PostSalaryTransactionParams) WithHTTPClient(client *http.Client) *PostSalaryTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post salary transaction params
func (o *PostSalaryTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post salary transaction params
func (o *PostSalaryTransactionParams) WithBody(body *models.SalaryTransaction) *PostSalaryTransactionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post salary transaction params
func (o *PostSalaryTransactionParams) SetBody(body *models.SalaryTransaction) {
	o.Body = body
}

// WithGenerateTaxDeduction adds the generateTaxDeduction to the post salary transaction params
func (o *PostSalaryTransactionParams) WithGenerateTaxDeduction(generateTaxDeduction *bool) *PostSalaryTransactionParams {
	o.SetGenerateTaxDeduction(generateTaxDeduction)
	return o
}

// SetGenerateTaxDeduction adds the generateTaxDeduction to the post salary transaction params
func (o *PostSalaryTransactionParams) SetGenerateTaxDeduction(generateTaxDeduction *bool) {
	o.GenerateTaxDeduction = generateTaxDeduction
}

// WriteToRequest writes these params to a swagger request
func (o *PostSalaryTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.GenerateTaxDeduction != nil {

		// query param generateTaxDeduction
		var qrGenerateTaxDeduction bool
		if o.GenerateTaxDeduction != nil {
			qrGenerateTaxDeduction = *o.GenerateTaxDeduction
		}
		qGenerateTaxDeduction := swag.FormatBool(qrGenerateTaxDeduction)
		if qGenerateTaxDeduction != "" {
			if err := r.SetQueryParam("generateTaxDeduction", qGenerateTaxDeduction); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
