// Code generated by go-swagger; DO NOT EDIT.

package employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetEmployeeIDReader is a Reader for the GetEmployeeID structure.
type GetEmployeeIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEmployeeIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEmployeeIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEmployeeIDOK creates a GetEmployeeIDOK with default headers values
func NewGetEmployeeIDOK() *GetEmployeeIDOK {
	return &GetEmployeeIDOK{}
}

/*GetEmployeeIDOK handles this case with default header values.

successful operation
*/
type GetEmployeeIDOK struct {
	Payload *models.ResponseWrapperEmployee
}

func (o *GetEmployeeIDOK) Error() string {
	return fmt.Sprintf("[GET /employee/{id}][%d] getEmployeeIdOK  %+v", 200, o.Payload)
}

func (o *GetEmployeeIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperEmployee)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
