// Code generated by go-swagger; DO NOT EDIT.

package employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPutEmployeeIDParams creates a new PutEmployeeIDParams object
// with the default values initialized.
func NewPutEmployeeIDParams() *PutEmployeeIDParams {
	var ()
	return &PutEmployeeIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutEmployeeIDParamsWithTimeout creates a new PutEmployeeIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutEmployeeIDParamsWithTimeout(timeout time.Duration) *PutEmployeeIDParams {
	var ()
	return &PutEmployeeIDParams{

		timeout: timeout,
	}
}

// NewPutEmployeeIDParamsWithContext creates a new PutEmployeeIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutEmployeeIDParamsWithContext(ctx context.Context) *PutEmployeeIDParams {
	var ()
	return &PutEmployeeIDParams{

		Context: ctx,
	}
}

// NewPutEmployeeIDParamsWithHTTPClient creates a new PutEmployeeIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutEmployeeIDParamsWithHTTPClient(client *http.Client) *PutEmployeeIDParams {
	var ()
	return &PutEmployeeIDParams{
		HTTPClient: client,
	}
}

/*PutEmployeeIDParams contains all the parameters to send to the API endpoint
for the put employee ID operation typically these are written to a http.Request
*/
type PutEmployeeIDParams struct {

	/*Body
	  Partial object describing what should be updated

	*/
	Body *models.Employee
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put employee ID params
func (o *PutEmployeeIDParams) WithTimeout(timeout time.Duration) *PutEmployeeIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put employee ID params
func (o *PutEmployeeIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put employee ID params
func (o *PutEmployeeIDParams) WithContext(ctx context.Context) *PutEmployeeIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put employee ID params
func (o *PutEmployeeIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put employee ID params
func (o *PutEmployeeIDParams) WithHTTPClient(client *http.Client) *PutEmployeeIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put employee ID params
func (o *PutEmployeeIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put employee ID params
func (o *PutEmployeeIDParams) WithBody(body *models.Employee) *PutEmployeeIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put employee ID params
func (o *PutEmployeeIDParams) SetBody(body *models.Employee) {
	o.Body = body
}

// WithID adds the id to the put employee ID params
func (o *PutEmployeeIDParams) WithID(id int32) *PutEmployeeIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put employee ID params
func (o *PutEmployeeIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutEmployeeIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
