// Code generated by go-swagger; DO NOT EDIT.

package travel_expense

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutTravelExpenseUnapproveParams creates a new PutTravelExpenseUnapproveParams object
// with the default values initialized.
func NewPutTravelExpenseUnapproveParams() *PutTravelExpenseUnapproveParams {
	var ()
	return &PutTravelExpenseUnapproveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutTravelExpenseUnapproveParamsWithTimeout creates a new PutTravelExpenseUnapproveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutTravelExpenseUnapproveParamsWithTimeout(timeout time.Duration) *PutTravelExpenseUnapproveParams {
	var ()
	return &PutTravelExpenseUnapproveParams{

		timeout: timeout,
	}
}

// NewPutTravelExpenseUnapproveParamsWithContext creates a new PutTravelExpenseUnapproveParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutTravelExpenseUnapproveParamsWithContext(ctx context.Context) *PutTravelExpenseUnapproveParams {
	var ()
	return &PutTravelExpenseUnapproveParams{

		Context: ctx,
	}
}

// NewPutTravelExpenseUnapproveParamsWithHTTPClient creates a new PutTravelExpenseUnapproveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutTravelExpenseUnapproveParamsWithHTTPClient(client *http.Client) *PutTravelExpenseUnapproveParams {
	var ()
	return &PutTravelExpenseUnapproveParams{
		HTTPClient: client,
	}
}

/*PutTravelExpenseUnapproveParams contains all the parameters to send to the API endpoint
for the put travel expense unapprove operation typically these are written to a http.Request
*/
type PutTravelExpenseUnapproveParams struct {

	/*ID
	  ID of the elements

	*/
	ID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put travel expense unapprove params
func (o *PutTravelExpenseUnapproveParams) WithTimeout(timeout time.Duration) *PutTravelExpenseUnapproveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put travel expense unapprove params
func (o *PutTravelExpenseUnapproveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put travel expense unapprove params
func (o *PutTravelExpenseUnapproveParams) WithContext(ctx context.Context) *PutTravelExpenseUnapproveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put travel expense unapprove params
func (o *PutTravelExpenseUnapproveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put travel expense unapprove params
func (o *PutTravelExpenseUnapproveParams) WithHTTPClient(client *http.Client) *PutTravelExpenseUnapproveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put travel expense unapprove params
func (o *PutTravelExpenseUnapproveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put travel expense unapprove params
func (o *PutTravelExpenseUnapproveParams) WithID(id *string) *PutTravelExpenseUnapproveParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put travel expense unapprove params
func (o *PutTravelExpenseUnapproveParams) SetID(id *string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTravelExpenseUnapproveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
