// Code generated by go-swagger; DO NOT EDIT.

package travel_expense

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutTravelExpenseCopyParams creates a new PutTravelExpenseCopyParams object
// with the default values initialized.
func NewPutTravelExpenseCopyParams() *PutTravelExpenseCopyParams {
	var ()
	return &PutTravelExpenseCopyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutTravelExpenseCopyParamsWithTimeout creates a new PutTravelExpenseCopyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutTravelExpenseCopyParamsWithTimeout(timeout time.Duration) *PutTravelExpenseCopyParams {
	var ()
	return &PutTravelExpenseCopyParams{

		timeout: timeout,
	}
}

// NewPutTravelExpenseCopyParamsWithContext creates a new PutTravelExpenseCopyParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutTravelExpenseCopyParamsWithContext(ctx context.Context) *PutTravelExpenseCopyParams {
	var ()
	return &PutTravelExpenseCopyParams{

		Context: ctx,
	}
}

// NewPutTravelExpenseCopyParamsWithHTTPClient creates a new PutTravelExpenseCopyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutTravelExpenseCopyParamsWithHTTPClient(client *http.Client) *PutTravelExpenseCopyParams {
	var ()
	return &PutTravelExpenseCopyParams{
		HTTPClient: client,
	}
}

/*PutTravelExpenseCopyParams contains all the parameters to send to the API endpoint
for the put travel expense copy operation typically these are written to a http.Request
*/
type PutTravelExpenseCopyParams struct {

	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put travel expense copy params
func (o *PutTravelExpenseCopyParams) WithTimeout(timeout time.Duration) *PutTravelExpenseCopyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put travel expense copy params
func (o *PutTravelExpenseCopyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put travel expense copy params
func (o *PutTravelExpenseCopyParams) WithContext(ctx context.Context) *PutTravelExpenseCopyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put travel expense copy params
func (o *PutTravelExpenseCopyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put travel expense copy params
func (o *PutTravelExpenseCopyParams) WithHTTPClient(client *http.Client) *PutTravelExpenseCopyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put travel expense copy params
func (o *PutTravelExpenseCopyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put travel expense copy params
func (o *PutTravelExpenseCopyParams) WithID(id int32) *PutTravelExpenseCopyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put travel expense copy params
func (o *PutTravelExpenseCopyParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTravelExpenseCopyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := swag.FormatInt32(qrID)
	if qID != "" {
		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
