// Code generated by go-swagger; DO NOT EDIT.

package travel_expense

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutTravelExpenseDeliverReader is a Reader for the PutTravelExpenseDeliver structure.
type PutTravelExpenseDeliverReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTravelExpenseDeliverReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutTravelExpenseDeliverOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutTravelExpenseDeliverOK creates a PutTravelExpenseDeliverOK with default headers values
func NewPutTravelExpenseDeliverOK() *PutTravelExpenseDeliverOK {
	return &PutTravelExpenseDeliverOK{}
}

/*PutTravelExpenseDeliverOK handles this case with default header values.

successful operation
*/
type PutTravelExpenseDeliverOK struct {
	Payload *models.ListResponseTravelExpense
}

func (o *PutTravelExpenseDeliverOK) Error() string {
	return fmt.Sprintf("[PUT /travelExpense/:deliver][%d] putTravelExpenseDeliverOK  %+v", 200, o.Payload)
}

func (o *PutTravelExpenseDeliverOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseTravelExpense)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
