// Code generated by go-swagger; DO NOT EDIT.

package travel_expense

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPutTravelExpenseIDParams creates a new PutTravelExpenseIDParams object
// with the default values initialized.
func NewPutTravelExpenseIDParams() *PutTravelExpenseIDParams {
	var ()
	return &PutTravelExpenseIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutTravelExpenseIDParamsWithTimeout creates a new PutTravelExpenseIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutTravelExpenseIDParamsWithTimeout(timeout time.Duration) *PutTravelExpenseIDParams {
	var ()
	return &PutTravelExpenseIDParams{

		timeout: timeout,
	}
}

// NewPutTravelExpenseIDParamsWithContext creates a new PutTravelExpenseIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutTravelExpenseIDParamsWithContext(ctx context.Context) *PutTravelExpenseIDParams {
	var ()
	return &PutTravelExpenseIDParams{

		Context: ctx,
	}
}

// NewPutTravelExpenseIDParamsWithHTTPClient creates a new PutTravelExpenseIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutTravelExpenseIDParamsWithHTTPClient(client *http.Client) *PutTravelExpenseIDParams {
	var ()
	return &PutTravelExpenseIDParams{
		HTTPClient: client,
	}
}

/*PutTravelExpenseIDParams contains all the parameters to send to the API endpoint
for the put travel expense ID operation typically these are written to a http.Request
*/
type PutTravelExpenseIDParams struct {

	/*Body
	  Partial object describing what should be updated

	*/
	Body *models.TravelExpense
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put travel expense ID params
func (o *PutTravelExpenseIDParams) WithTimeout(timeout time.Duration) *PutTravelExpenseIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put travel expense ID params
func (o *PutTravelExpenseIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put travel expense ID params
func (o *PutTravelExpenseIDParams) WithContext(ctx context.Context) *PutTravelExpenseIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put travel expense ID params
func (o *PutTravelExpenseIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put travel expense ID params
func (o *PutTravelExpenseIDParams) WithHTTPClient(client *http.Client) *PutTravelExpenseIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put travel expense ID params
func (o *PutTravelExpenseIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put travel expense ID params
func (o *PutTravelExpenseIDParams) WithBody(body *models.TravelExpense) *PutTravelExpenseIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put travel expense ID params
func (o *PutTravelExpenseIDParams) SetBody(body *models.TravelExpense) {
	o.Body = body
}

// WithID adds the id to the put travel expense ID params
func (o *PutTravelExpenseIDParams) WithID(id int32) *PutTravelExpenseIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put travel expense ID params
func (o *PutTravelExpenseIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTravelExpenseIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
