// Code generated by go-swagger; DO NOT EDIT.

package travel_expense

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutTravelExpenseApproveParams creates a new PutTravelExpenseApproveParams object
// with the default values initialized.
func NewPutTravelExpenseApproveParams() *PutTravelExpenseApproveParams {
	var ()
	return &PutTravelExpenseApproveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutTravelExpenseApproveParamsWithTimeout creates a new PutTravelExpenseApproveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutTravelExpenseApproveParamsWithTimeout(timeout time.Duration) *PutTravelExpenseApproveParams {
	var ()
	return &PutTravelExpenseApproveParams{

		timeout: timeout,
	}
}

// NewPutTravelExpenseApproveParamsWithContext creates a new PutTravelExpenseApproveParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutTravelExpenseApproveParamsWithContext(ctx context.Context) *PutTravelExpenseApproveParams {
	var ()
	return &PutTravelExpenseApproveParams{

		Context: ctx,
	}
}

// NewPutTravelExpenseApproveParamsWithHTTPClient creates a new PutTravelExpenseApproveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutTravelExpenseApproveParamsWithHTTPClient(client *http.Client) *PutTravelExpenseApproveParams {
	var ()
	return &PutTravelExpenseApproveParams{
		HTTPClient: client,
	}
}

/*PutTravelExpenseApproveParams contains all the parameters to send to the API endpoint
for the put travel expense approve operation typically these are written to a http.Request
*/
type PutTravelExpenseApproveParams struct {

	/*ID
	  ID of the elements

	*/
	ID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put travel expense approve params
func (o *PutTravelExpenseApproveParams) WithTimeout(timeout time.Duration) *PutTravelExpenseApproveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put travel expense approve params
func (o *PutTravelExpenseApproveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put travel expense approve params
func (o *PutTravelExpenseApproveParams) WithContext(ctx context.Context) *PutTravelExpenseApproveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put travel expense approve params
func (o *PutTravelExpenseApproveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put travel expense approve params
func (o *PutTravelExpenseApproveParams) WithHTTPClient(client *http.Client) *PutTravelExpenseApproveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put travel expense approve params
func (o *PutTravelExpenseApproveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put travel expense approve params
func (o *PutTravelExpenseApproveParams) WithID(id *string) *PutTravelExpenseApproveParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put travel expense approve params
func (o *PutTravelExpenseApproveParams) SetID(id *string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTravelExpenseApproveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
