// Code generated by go-swagger; DO NOT EDIT.

package statement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PostBankStatementImportReader is a Reader for the PostBankStatementImport structure.
type PostBankStatementImportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBankStatementImportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostBankStatementImportCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostBankStatementImportCreated creates a PostBankStatementImportCreated with default headers values
func NewPostBankStatementImportCreated() *PostBankStatementImportCreated {
	return &PostBankStatementImportCreated{}
}

/*PostBankStatementImportCreated handles this case with default header values.

successfully created
*/
type PostBankStatementImportCreated struct {
	Payload *models.ResponseWrapperBankStatement
}

func (o *PostBankStatementImportCreated) Error() string {
	return fmt.Sprintf("[POST /bank/statement/import][%d] postBankStatementImportCreated  %+v", 201, o.Payload)
}

func (o *PostBankStatementImportCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperBankStatement)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
