// Code generated by go-swagger; DO NOT EDIT.

package voucher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPutLedgerVoucherIDParams creates a new PutLedgerVoucherIDParams object
// with the default values initialized.
func NewPutLedgerVoucherIDParams() *PutLedgerVoucherIDParams {
	var (
		sendToLedgerDefault = bool(true)
	)
	return &PutLedgerVoucherIDParams{
		SendToLedger: &sendToLedgerDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPutLedgerVoucherIDParamsWithTimeout creates a new PutLedgerVoucherIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutLedgerVoucherIDParamsWithTimeout(timeout time.Duration) *PutLedgerVoucherIDParams {
	var (
		sendToLedgerDefault = bool(true)
	)
	return &PutLedgerVoucherIDParams{
		SendToLedger: &sendToLedgerDefault,

		timeout: timeout,
	}
}

// NewPutLedgerVoucherIDParamsWithContext creates a new PutLedgerVoucherIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutLedgerVoucherIDParamsWithContext(ctx context.Context) *PutLedgerVoucherIDParams {
	var (
		sendToLedgerDefault = bool(true)
	)
	return &PutLedgerVoucherIDParams{
		SendToLedger: &sendToLedgerDefault,

		Context: ctx,
	}
}

// NewPutLedgerVoucherIDParamsWithHTTPClient creates a new PutLedgerVoucherIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutLedgerVoucherIDParamsWithHTTPClient(client *http.Client) *PutLedgerVoucherIDParams {
	var (
		sendToLedgerDefault = bool(true)
	)
	return &PutLedgerVoucherIDParams{
		SendToLedger: &sendToLedgerDefault,
		HTTPClient:   client,
	}
}

/*PutLedgerVoucherIDParams contains all the parameters to send to the API endpoint
for the put ledger voucher ID operation typically these are written to a http.Request
*/
type PutLedgerVoucherIDParams struct {

	/*Body
	  Partial object describing what should be updated

	*/
	Body *models.Voucher
	/*ID
	  Element ID

	*/
	ID int32
	/*SendToLedger
	  Should the voucher be sent to ledger? Requires the "Advanced Voucher" permission.

	*/
	SendToLedger *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) WithTimeout(timeout time.Duration) *PutLedgerVoucherIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) WithContext(ctx context.Context) *PutLedgerVoucherIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) WithHTTPClient(client *http.Client) *PutLedgerVoucherIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) WithBody(body *models.Voucher) *PutLedgerVoucherIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) SetBody(body *models.Voucher) {
	o.Body = body
}

// WithID adds the id to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) WithID(id int32) *PutLedgerVoucherIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) SetID(id int32) {
	o.ID = id
}

// WithSendToLedger adds the sendToLedger to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) WithSendToLedger(sendToLedger *bool) *PutLedgerVoucherIDParams {
	o.SetSendToLedger(sendToLedger)
	return o
}

// SetSendToLedger adds the sendToLedger to the put ledger voucher ID params
func (o *PutLedgerVoucherIDParams) SetSendToLedger(sendToLedger *bool) {
	o.SendToLedger = sendToLedger
}

// WriteToRequest writes these params to a swagger request
func (o *PutLedgerVoucherIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.SendToLedger != nil {

		// query param sendToLedger
		var qrSendToLedger bool
		if o.SendToLedger != nil {
			qrSendToLedger = *o.SendToLedger
		}
		qSendToLedger := swag.FormatBool(qrSendToLedger)
		if qSendToLedger != "" {
			if err := r.SetQueryParam("sendToLedger", qSendToLedger); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
