// Code generated by go-swagger; DO NOT EDIT.

package voucher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutLedgerVoucherIDReverseReader is a Reader for the PutLedgerVoucherIDReverse structure.
type PutLedgerVoucherIDReverseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutLedgerVoucherIDReverseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutLedgerVoucherIDReverseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutLedgerVoucherIDReverseOK creates a PutLedgerVoucherIDReverseOK with default headers values
func NewPutLedgerVoucherIDReverseOK() *PutLedgerVoucherIDReverseOK {
	return &PutLedgerVoucherIDReverseOK{}
}

/*PutLedgerVoucherIDReverseOK handles this case with default header values.

successful operation
*/
type PutLedgerVoucherIDReverseOK struct {
	Payload *models.ResponseWrapperVoucher
}

func (o *PutLedgerVoucherIDReverseOK) Error() string {
	return fmt.Sprintf("[PUT /ledger/voucher/{id}/:reverse][%d] putLedgerVoucherIdReverseOK  %+v", 200, o.Payload)
}

func (o *PutLedgerVoucherIDReverseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperVoucher)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
