// Code generated by go-swagger; DO NOT EDIT.

package participant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PostProjectParticipantReader is a Reader for the PostProjectParticipant structure.
type PostProjectParticipantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectParticipantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostProjectParticipantCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostProjectParticipantCreated creates a PostProjectParticipantCreated with default headers values
func NewPostProjectParticipantCreated() *PostProjectParticipantCreated {
	return &PostProjectParticipantCreated{}
}

/*PostProjectParticipantCreated handles this case with default header values.

successfully created
*/
type PostProjectParticipantCreated struct {
	Payload *models.ResponseWrapperProjectParticipant
}

func (o *PostProjectParticipantCreated) Error() string {
	return fmt.Sprintf("[POST /project/participant][%d] postProjectParticipantCreated  %+v", 201, o.Payload)
}

func (o *PostProjectParticipantCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperProjectParticipant)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
