// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLedgerAccountListReader is a Reader for the DeleteLedgerAccountList structure.
type DeleteLedgerAccountListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLedgerAccountListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteLedgerAccountListDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteLedgerAccountListDefault creates a DeleteLedgerAccountListDefault with default headers values
func NewDeleteLedgerAccountListDefault(code int) *DeleteLedgerAccountListDefault {
	return &DeleteLedgerAccountListDefault{
		_statusCode: code,
	}
}

/*DeleteLedgerAccountListDefault handles this case with default header values.

successful operation
*/
type DeleteLedgerAccountListDefault struct {
	_statusCode int
}

// Code gets the status code for the delete ledger account list default response
func (o *DeleteLedgerAccountListDefault) Code() int {
	return o._statusCode
}

func (o *DeleteLedgerAccountListDefault) Error() string {
	return fmt.Sprintf("[DELETE /ledger/account/list][%d] DeleteLedgerAccountList default ", o._statusCode)
}

func (o *DeleteLedgerAccountListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
