// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteLedgerAccountListParams creates a new DeleteLedgerAccountListParams object
// with the default values initialized.
func NewDeleteLedgerAccountListParams() *DeleteLedgerAccountListParams {
	var ()
	return &DeleteLedgerAccountListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLedgerAccountListParamsWithTimeout creates a new DeleteLedgerAccountListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteLedgerAccountListParamsWithTimeout(timeout time.Duration) *DeleteLedgerAccountListParams {
	var ()
	return &DeleteLedgerAccountListParams{

		timeout: timeout,
	}
}

// NewDeleteLedgerAccountListParamsWithContext creates a new DeleteLedgerAccountListParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteLedgerAccountListParamsWithContext(ctx context.Context) *DeleteLedgerAccountListParams {
	var ()
	return &DeleteLedgerAccountListParams{

		Context: ctx,
	}
}

// NewDeleteLedgerAccountListParamsWithHTTPClient creates a new DeleteLedgerAccountListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteLedgerAccountListParamsWithHTTPClient(client *http.Client) *DeleteLedgerAccountListParams {
	var ()
	return &DeleteLedgerAccountListParams{
		HTTPClient: client,
	}
}

/*DeleteLedgerAccountListParams contains all the parameters to send to the API endpoint
for the delete ledger account list operation typically these are written to a http.Request
*/
type DeleteLedgerAccountListParams struct {

	/*Ids
	  ID of the elements

	*/
	Ids string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete ledger account list params
func (o *DeleteLedgerAccountListParams) WithTimeout(timeout time.Duration) *DeleteLedgerAccountListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete ledger account list params
func (o *DeleteLedgerAccountListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete ledger account list params
func (o *DeleteLedgerAccountListParams) WithContext(ctx context.Context) *DeleteLedgerAccountListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete ledger account list params
func (o *DeleteLedgerAccountListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete ledger account list params
func (o *DeleteLedgerAccountListParams) WithHTTPClient(client *http.Client) *DeleteLedgerAccountListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete ledger account list params
func (o *DeleteLedgerAccountListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIds adds the ids to the delete ledger account list params
func (o *DeleteLedgerAccountListParams) WithIds(ids string) *DeleteLedgerAccountListParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the delete ledger account list params
func (o *DeleteLedgerAccountListParams) SetIds(ids string) {
	o.Ids = ids
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLedgerAccountListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param ids
	qrIds := o.Ids
	qIds := qrIds
	if qIds != "" {
		if err := r.SetQueryParam("ids", qIds); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
