// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLedgerAccountIDParams creates a new GetLedgerAccountIDParams object
// with the default values initialized.
func NewGetLedgerAccountIDParams() *GetLedgerAccountIDParams {
	var ()
	return &GetLedgerAccountIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLedgerAccountIDParamsWithTimeout creates a new GetLedgerAccountIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLedgerAccountIDParamsWithTimeout(timeout time.Duration) *GetLedgerAccountIDParams {
	var ()
	return &GetLedgerAccountIDParams{

		timeout: timeout,
	}
}

// NewGetLedgerAccountIDParamsWithContext creates a new GetLedgerAccountIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLedgerAccountIDParamsWithContext(ctx context.Context) *GetLedgerAccountIDParams {
	var ()
	return &GetLedgerAccountIDParams{

		Context: ctx,
	}
}

// NewGetLedgerAccountIDParamsWithHTTPClient creates a new GetLedgerAccountIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLedgerAccountIDParamsWithHTTPClient(client *http.Client) *GetLedgerAccountIDParams {
	var ()
	return &GetLedgerAccountIDParams{
		HTTPClient: client,
	}
}

/*GetLedgerAccountIDParams contains all the parameters to send to the API endpoint
for the get ledger account ID operation typically these are written to a http.Request
*/
type GetLedgerAccountIDParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get ledger account ID params
func (o *GetLedgerAccountIDParams) WithTimeout(timeout time.Duration) *GetLedgerAccountIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ledger account ID params
func (o *GetLedgerAccountIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ledger account ID params
func (o *GetLedgerAccountIDParams) WithContext(ctx context.Context) *GetLedgerAccountIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ledger account ID params
func (o *GetLedgerAccountIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ledger account ID params
func (o *GetLedgerAccountIDParams) WithHTTPClient(client *http.Client) *GetLedgerAccountIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ledger account ID params
func (o *GetLedgerAccountIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get ledger account ID params
func (o *GetLedgerAccountIDParams) WithFields(fields *string) *GetLedgerAccountIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get ledger account ID params
func (o *GetLedgerAccountIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the get ledger account ID params
func (o *GetLedgerAccountIDParams) WithID(id int32) *GetLedgerAccountIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get ledger account ID params
func (o *GetLedgerAccountIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetLedgerAccountIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
