// Code generated by go-swagger; DO NOT EDIT.

package annual_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new annual account API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for annual account API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetLedgerAnnualAccount finds annual accounts corresponding with sent data
*/
func (a *Client) GetLedgerAnnualAccount(params *GetLedgerAnnualAccountParams, authInfo runtime.ClientAuthInfoWriter) (*GetLedgerAnnualAccountOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLedgerAnnualAccountParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetLedgerAnnualAccount",
		Method:             "GET",
		PathPattern:        "/ledger/annualAccount",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLedgerAnnualAccountReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetLedgerAnnualAccountOK), nil

}

/*
GetLedgerAnnualAccountID gets annual account by ID
*/
func (a *Client) GetLedgerAnnualAccountID(params *GetLedgerAnnualAccountIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetLedgerAnnualAccountIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLedgerAnnualAccountIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetLedgerAnnualAccountID",
		Method:             "GET",
		PathPattern:        "/ledger/annualAccount/{id}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLedgerAnnualAccountIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetLedgerAnnualAccountIDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
