// Code generated by go-swagger; DO NOT EDIT.

package annual_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetLedgerAnnualAccountIDReader is a Reader for the GetLedgerAnnualAccountID structure.
type GetLedgerAnnualAccountIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLedgerAnnualAccountIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetLedgerAnnualAccountIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLedgerAnnualAccountIDOK creates a GetLedgerAnnualAccountIDOK with default headers values
func NewGetLedgerAnnualAccountIDOK() *GetLedgerAnnualAccountIDOK {
	return &GetLedgerAnnualAccountIDOK{}
}

/*GetLedgerAnnualAccountIDOK handles this case with default header values.

successful operation
*/
type GetLedgerAnnualAccountIDOK struct {
	Payload *models.ResponseWrapperAnnualAccount
}

func (o *GetLedgerAnnualAccountIDOK) Error() string {
	return fmt.Sprintf("[GET /ledger/annualAccount/{id}][%d] getLedgerAnnualAccountIdOK  %+v", 200, o.Payload)
}

func (o *GetLedgerAnnualAccountIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperAnnualAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
