// Code generated by go-swagger; DO NOT EDIT.

package annual_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLedgerAnnualAccountIDParams creates a new GetLedgerAnnualAccountIDParams object
// with the default values initialized.
func NewGetLedgerAnnualAccountIDParams() *GetLedgerAnnualAccountIDParams {
	var ()
	return &GetLedgerAnnualAccountIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLedgerAnnualAccountIDParamsWithTimeout creates a new GetLedgerAnnualAccountIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLedgerAnnualAccountIDParamsWithTimeout(timeout time.Duration) *GetLedgerAnnualAccountIDParams {
	var ()
	return &GetLedgerAnnualAccountIDParams{

		timeout: timeout,
	}
}

// NewGetLedgerAnnualAccountIDParamsWithContext creates a new GetLedgerAnnualAccountIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLedgerAnnualAccountIDParamsWithContext(ctx context.Context) *GetLedgerAnnualAccountIDParams {
	var ()
	return &GetLedgerAnnualAccountIDParams{

		Context: ctx,
	}
}

// NewGetLedgerAnnualAccountIDParamsWithHTTPClient creates a new GetLedgerAnnualAccountIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLedgerAnnualAccountIDParamsWithHTTPClient(client *http.Client) *GetLedgerAnnualAccountIDParams {
	var ()
	return &GetLedgerAnnualAccountIDParams{
		HTTPClient: client,
	}
}

/*GetLedgerAnnualAccountIDParams contains all the parameters to send to the API endpoint
for the get ledger annual account ID operation typically these are written to a http.Request
*/
type GetLedgerAnnualAccountIDParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) WithTimeout(timeout time.Duration) *GetLedgerAnnualAccountIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) WithContext(ctx context.Context) *GetLedgerAnnualAccountIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) WithHTTPClient(client *http.Client) *GetLedgerAnnualAccountIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) WithFields(fields *string) *GetLedgerAnnualAccountIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) WithID(id int32) *GetLedgerAnnualAccountIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get ledger annual account ID params
func (o *GetLedgerAnnualAccountIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetLedgerAnnualAccountIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
