// Code generated by go-swagger; DO NOT EDIT.

package standard_time

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetEmployeeStandardTimeIDReader is a Reader for the GetEmployeeStandardTimeID structure.
type GetEmployeeStandardTimeIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEmployeeStandardTimeIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEmployeeStandardTimeIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEmployeeStandardTimeIDOK creates a GetEmployeeStandardTimeIDOK with default headers values
func NewGetEmployeeStandardTimeIDOK() *GetEmployeeStandardTimeIDOK {
	return &GetEmployeeStandardTimeIDOK{}
}

/*GetEmployeeStandardTimeIDOK handles this case with default header values.

successful operation
*/
type GetEmployeeStandardTimeIDOK struct {
	Payload *models.ResponseWrapperStandardTime
}

func (o *GetEmployeeStandardTimeIDOK) Error() string {
	return fmt.Sprintf("[GET /employee/standardTime/{id}][%d] getEmployeeStandardTimeIdOK  %+v", 200, o.Payload)
}

func (o *GetEmployeeStandardTimeIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperStandardTime)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
