// Code generated by go-swagger; DO NOT EDIT.

package payment_type_out

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLedgerPaymentTypeOutIDReader is a Reader for the DeleteLedgerPaymentTypeOutID structure.
type DeleteLedgerPaymentTypeOutIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLedgerPaymentTypeOutIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteLedgerPaymentTypeOutIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteLedgerPaymentTypeOutIDDefault creates a DeleteLedgerPaymentTypeOutIDDefault with default headers values
func NewDeleteLedgerPaymentTypeOutIDDefault(code int) *DeleteLedgerPaymentTypeOutIDDefault {
	return &DeleteLedgerPaymentTypeOutIDDefault{
		_statusCode: code,
	}
}

/*DeleteLedgerPaymentTypeOutIDDefault handles this case with default header values.

successful operation
*/
type DeleteLedgerPaymentTypeOutIDDefault struct {
	_statusCode int
}

// Code gets the status code for the delete ledger payment type out ID default response
func (o *DeleteLedgerPaymentTypeOutIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteLedgerPaymentTypeOutIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /ledger/paymentTypeOut/{id}][%d] DeleteLedgerPaymentTypeOutID default ", o._statusCode)
}

func (o *DeleteLedgerPaymentTypeOutIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
