// Code generated by go-swagger; DO NOT EDIT.

package payment_type_out

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PostLedgerPaymentTypeOutReader is a Reader for the PostLedgerPaymentTypeOut structure.
type PostLedgerPaymentTypeOutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLedgerPaymentTypeOutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostLedgerPaymentTypeOutCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLedgerPaymentTypeOutCreated creates a PostLedgerPaymentTypeOutCreated with default headers values
func NewPostLedgerPaymentTypeOutCreated() *PostLedgerPaymentTypeOutCreated {
	return &PostLedgerPaymentTypeOutCreated{}
}

/*PostLedgerPaymentTypeOutCreated handles this case with default header values.

successfully created
*/
type PostLedgerPaymentTypeOutCreated struct {
	Payload *models.ResponseWrapperPaymentTypeOut
}

func (o *PostLedgerPaymentTypeOutCreated) Error() string {
	return fmt.Sprintf("[POST /ledger/paymentTypeOut][%d] postLedgerPaymentTypeOutCreated  %+v", 201, o.Payload)
}

func (o *PostLedgerPaymentTypeOutCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperPaymentTypeOut)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
