// Code generated by go-swagger; DO NOT EDIT.

package payment_type_out

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PostLedgerPaymentTypeOutListReader is a Reader for the PostLedgerPaymentTypeOutList structure.
type PostLedgerPaymentTypeOutListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLedgerPaymentTypeOutListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostLedgerPaymentTypeOutListCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLedgerPaymentTypeOutListCreated creates a PostLedgerPaymentTypeOutListCreated with default headers values
func NewPostLedgerPaymentTypeOutListCreated() *PostLedgerPaymentTypeOutListCreated {
	return &PostLedgerPaymentTypeOutListCreated{}
}

/*PostLedgerPaymentTypeOutListCreated handles this case with default header values.

successfully created
*/
type PostLedgerPaymentTypeOutListCreated struct {
	Payload *models.ListResponsePaymentTypeOut
}

func (o *PostLedgerPaymentTypeOutListCreated) Error() string {
	return fmt.Sprintf("[POST /ledger/paymentTypeOut/list][%d] postLedgerPaymentTypeOutListCreated  %+v", 201, o.Payload)
}

func (o *PostLedgerPaymentTypeOutListCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponsePaymentTypeOut)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
