// Code generated by go-swagger; DO NOT EDIT.

package orderline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteOrderOrderlineIDReader is a Reader for the DeleteOrderOrderlineID structure.
type DeleteOrderOrderlineIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrderOrderlineIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteOrderOrderlineIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteOrderOrderlineIDDefault creates a DeleteOrderOrderlineIDDefault with default headers values
func NewDeleteOrderOrderlineIDDefault(code int) *DeleteOrderOrderlineIDDefault {
	return &DeleteOrderOrderlineIDDefault{
		_statusCode: code,
	}
}

/*DeleteOrderOrderlineIDDefault handles this case with default header values.

successful operation
*/
type DeleteOrderOrderlineIDDefault struct {
	_statusCode int
}

// Code gets the status code for the delete order orderline ID default response
func (o *DeleteOrderOrderlineIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteOrderOrderlineIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /order/orderline/{id}][%d] DeleteOrderOrderlineID default ", o._statusCode)
}

func (o *DeleteOrderOrderlineIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
