// Code generated by go-swagger; DO NOT EDIT.

package orderline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutProjectOrderlineIDReader is a Reader for the PutProjectOrderlineID structure.
type PutProjectOrderlineIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutProjectOrderlineIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutProjectOrderlineIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutProjectOrderlineIDOK creates a PutProjectOrderlineIDOK with default headers values
func NewPutProjectOrderlineIDOK() *PutProjectOrderlineIDOK {
	return &PutProjectOrderlineIDOK{}
}

/*PutProjectOrderlineIDOK handles this case with default header values.

successful operation
*/
type PutProjectOrderlineIDOK struct {
	Payload *models.ResponseWrapperProjectOrderLine
}

func (o *PutProjectOrderlineIDOK) Error() string {
	return fmt.Sprintf("[PUT /project/orderline/{id}][%d] putProjectOrderlineIdOK  %+v", 200, o.Payload)
}

func (o *PutProjectOrderlineIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperProjectOrderLine)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
