// Code generated by go-swagger; DO NOT EDIT.

package prospect

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetCrmProspectReader is a Reader for the GetCrmProspect structure.
type GetCrmProspectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCrmProspectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCrmProspectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCrmProspectOK creates a GetCrmProspectOK with default headers values
func NewGetCrmProspectOK() *GetCrmProspectOK {
	return &GetCrmProspectOK{}
}

/*GetCrmProspectOK handles this case with default header values.

successful operation
*/
type GetCrmProspectOK struct {
	Payload *models.ListResponseProspect
}

func (o *GetCrmProspectOK) Error() string {
	return fmt.Sprintf("[GET /crm/prospect][%d] getCrmProspectOK  %+v", 200, o.Payload)
}

func (o *GetCrmProspectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseProspect)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
