// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// GetInvoiceDetailsIDReader is a Reader for the GetInvoiceDetailsID structure.
type GetInvoiceDetailsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInvoiceDetailsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInvoiceDetailsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInvoiceDetailsIDOK creates a GetInvoiceDetailsIDOK with default headers values
func NewGetInvoiceDetailsIDOK() *GetInvoiceDetailsIDOK {
	return &GetInvoiceDetailsIDOK{}
}

/*GetInvoiceDetailsIDOK handles this case with default header values.

successful operation
*/
type GetInvoiceDetailsIDOK struct {
	Payload *models.ResponseWrapperProjectInvoiceDetails
}

func (o *GetInvoiceDetailsIDOK) Error() string {
	return fmt.Sprintf("[GET /invoice/details/{id}][%d] getInvoiceDetailsIdOK  %+v", 200, o.Payload)
}

func (o *GetInvoiceDetailsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperProjectInvoiceDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
