// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutEmployeeEmploymentDetailsIDReader is a Reader for the PutEmployeeEmploymentDetailsID structure.
type PutEmployeeEmploymentDetailsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutEmployeeEmploymentDetailsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutEmployeeEmploymentDetailsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutEmployeeEmploymentDetailsIDOK creates a PutEmployeeEmploymentDetailsIDOK with default headers values
func NewPutEmployeeEmploymentDetailsIDOK() *PutEmployeeEmploymentDetailsIDOK {
	return &PutEmployeeEmploymentDetailsIDOK{}
}

/*PutEmployeeEmploymentDetailsIDOK handles this case with default header values.

successful operation
*/
type PutEmployeeEmploymentDetailsIDOK struct {
	Payload *models.ResponseWrapperEmploymentDetails
}

func (o *PutEmployeeEmploymentDetailsIDOK) Error() string {
	return fmt.Sprintf("[PUT /employee/employment/details/{id}][%d] putEmployeeEmploymentDetailsIdOK  %+v", 200, o.Payload)
}

func (o *PutEmployeeEmploymentDetailsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperEmploymentDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
