// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PutAddressIDReader is a Reader for the PutAddressID structure.
type PutAddressIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAddressIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutAddressIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAddressIDOK creates a PutAddressIDOK with default headers values
func NewPutAddressIDOK() *PutAddressIDOK {
	return &PutAddressIDOK{}
}

/*PutAddressIDOK handles this case with default header values.

successful operation
*/
type PutAddressIDOK struct {
	Payload *models.ResponseWrapperAddress
}

func (o *PutAddressIDOK) Error() string {
	return fmt.Sprintf("[PUT /address/{id}][%d] putAddressIdOK  %+v", 200, o.Payload)
}

func (o *PutAddressIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperAddress)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
