// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPostProjectListParams creates a new PostProjectListParams object
// with the default values initialized.
func NewPostProjectListParams() *PostProjectListParams {
	var ()
	return &PostProjectListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostProjectListParamsWithTimeout creates a new PostProjectListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostProjectListParamsWithTimeout(timeout time.Duration) *PostProjectListParams {
	var ()
	return &PostProjectListParams{

		timeout: timeout,
	}
}

// NewPostProjectListParamsWithContext creates a new PostProjectListParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostProjectListParamsWithContext(ctx context.Context) *PostProjectListParams {
	var ()
	return &PostProjectListParams{

		Context: ctx,
	}
}

// NewPostProjectListParamsWithHTTPClient creates a new PostProjectListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostProjectListParamsWithHTTPClient(client *http.Client) *PostProjectListParams {
	var ()
	return &PostProjectListParams{
		HTTPClient: client,
	}
}

/*PostProjectListParams contains all the parameters to send to the API endpoint
for the post project list operation typically these are written to a http.Request
*/
type PostProjectListParams struct {

	/*Body
	  JSON representing a list of new object to be created. Should not have ID and version set.

	*/
	Body []*models.Project

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post project list params
func (o *PostProjectListParams) WithTimeout(timeout time.Duration) *PostProjectListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post project list params
func (o *PostProjectListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post project list params
func (o *PostProjectListParams) WithContext(ctx context.Context) *PostProjectListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post project list params
func (o *PostProjectListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post project list params
func (o *PostProjectListParams) WithHTTPClient(client *http.Client) *PostProjectListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post project list params
func (o *PostProjectListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post project list params
func (o *PostProjectListParams) WithBody(body []*models.Project) *PostProjectListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post project list params
func (o *PostProjectListParams) SetBody(body []*models.Project) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostProjectListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
