// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PostProjectListReader is a Reader for the PostProjectList structure.
type PostProjectListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostProjectListCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostProjectListCreated creates a PostProjectListCreated with default headers values
func NewPostProjectListCreated() *PostProjectListCreated {
	return &PostProjectListCreated{}
}

/*PostProjectListCreated handles this case with default header values.

successfully created
*/
type PostProjectListCreated struct {
	Payload *models.ListResponseProject
}

func (o *PostProjectListCreated) Error() string {
	return fmt.Sprintf("[POST /project/list][%d] postProjectListCreated  %+v", 201, o.Payload)
}

func (o *PostProjectListCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListResponseProject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
