// Code generated by go-swagger; DO NOT EDIT.

package supplier

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// PostSupplierReader is a Reader for the PostSupplier structure.
type PostSupplierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSupplierReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostSupplierCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSupplierCreated creates a PostSupplierCreated with default headers values
func NewPostSupplierCreated() *PostSupplierCreated {
	return &PostSupplierCreated{}
}

/*PostSupplierCreated handles this case with default header values.

successfully created
*/
type PostSupplierCreated struct {
	Payload *models.ResponseWrapperSupplier
}

func (o *PostSupplierCreated) Error() string {
	return fmt.Sprintf("[POST /supplier][%d] postSupplierCreated  %+v", 201, o.Payload)
}

func (o *PostSupplierCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseWrapperSupplier)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
