// Code generated by go-swagger; DO NOT EDIT.

package supplier

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/PrakharSrivastav/Petstore/models"
)

// NewPutSupplierIDParams creates a new PutSupplierIDParams object
// with the default values initialized.
func NewPutSupplierIDParams() *PutSupplierIDParams {
	var ()
	return &PutSupplierIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutSupplierIDParamsWithTimeout creates a new PutSupplierIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutSupplierIDParamsWithTimeout(timeout time.Duration) *PutSupplierIDParams {
	var ()
	return &PutSupplierIDParams{

		timeout: timeout,
	}
}

// NewPutSupplierIDParamsWithContext creates a new PutSupplierIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutSupplierIDParamsWithContext(ctx context.Context) *PutSupplierIDParams {
	var ()
	return &PutSupplierIDParams{

		Context: ctx,
	}
}

// NewPutSupplierIDParamsWithHTTPClient creates a new PutSupplierIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutSupplierIDParamsWithHTTPClient(client *http.Client) *PutSupplierIDParams {
	var ()
	return &PutSupplierIDParams{
		HTTPClient: client,
	}
}

/*PutSupplierIDParams contains all the parameters to send to the API endpoint
for the put supplier ID operation typically these are written to a http.Request
*/
type PutSupplierIDParams struct {

	/*Body
	  Partial object describing what should be updated

	*/
	Body *models.Supplier
	/*ID
	  Element ID

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put supplier ID params
func (o *PutSupplierIDParams) WithTimeout(timeout time.Duration) *PutSupplierIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put supplier ID params
func (o *PutSupplierIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put supplier ID params
func (o *PutSupplierIDParams) WithContext(ctx context.Context) *PutSupplierIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put supplier ID params
func (o *PutSupplierIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put supplier ID params
func (o *PutSupplierIDParams) WithHTTPClient(client *http.Client) *PutSupplierIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put supplier ID params
func (o *PutSupplierIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put supplier ID params
func (o *PutSupplierIDParams) WithBody(body *models.Supplier) *PutSupplierIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put supplier ID params
func (o *PutSupplierIDParams) SetBody(body *models.Supplier) {
	o.Body = body
}

// WithID adds the id to the put supplier ID params
func (o *PutSupplierIDParams) WithID(id int32) *PutSupplierIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put supplier ID params
func (o *PutSupplierIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutSupplierIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
