// Code generated by go-swagger; DO NOT EDIT.

package consumer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTokenConsumerByTokenParams creates a new GetTokenConsumerByTokenParams object
// with the default values initialized.
func NewGetTokenConsumerByTokenParams() *GetTokenConsumerByTokenParams {
	var ()
	return &GetTokenConsumerByTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTokenConsumerByTokenParamsWithTimeout creates a new GetTokenConsumerByTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTokenConsumerByTokenParamsWithTimeout(timeout time.Duration) *GetTokenConsumerByTokenParams {
	var ()
	return &GetTokenConsumerByTokenParams{

		timeout: timeout,
	}
}

// NewGetTokenConsumerByTokenParamsWithContext creates a new GetTokenConsumerByTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTokenConsumerByTokenParamsWithContext(ctx context.Context) *GetTokenConsumerByTokenParams {
	var ()
	return &GetTokenConsumerByTokenParams{

		Context: ctx,
	}
}

// NewGetTokenConsumerByTokenParamsWithHTTPClient creates a new GetTokenConsumerByTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTokenConsumerByTokenParamsWithHTTPClient(client *http.Client) *GetTokenConsumerByTokenParams {
	var ()
	return &GetTokenConsumerByTokenParams{
		HTTPClient: client,
	}
}

/*GetTokenConsumerByTokenParams contains all the parameters to send to the API endpoint
for the get token consumer by token operation typically these are written to a http.Request
*/
type GetTokenConsumerByTokenParams struct {

	/*Fields
	  Fields filter pattern

	*/
	Fields *string
	/*Token
	  Element ID

	*/
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) WithTimeout(timeout time.Duration) *GetTokenConsumerByTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) WithContext(ctx context.Context) *GetTokenConsumerByTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) WithHTTPClient(client *http.Client) *GetTokenConsumerByTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) WithFields(fields *string) *GetTokenConsumerByTokenParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithToken adds the token to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) WithToken(token string) *GetTokenConsumerByTokenParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get token consumer by token params
func (o *GetTokenConsumerByTokenParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *GetTokenConsumerByTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// query param token
	qrToken := o.Token
	qToken := qrToken
	if qToken != "" {
		if err := r.SetQueryParam("token", qToken); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
